import {governance} from '../key-governance/route';
import {identity,db,failure,body,text,accessProject,activity,HttpError} from '../shared';
const headers={'Cache-Control':'private, no-store'};
export async function keyHash(key:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key))),b=>b.toString(16).padStart(2,'0')).join('')}
const fields='k.id,k.label,k.project AS projectId,p.title AS projectTitle,k.prefix,k.created AS createdAt,k.expires AS expiresAt,k.last_used AS lastUsedAt,k.revoked AS revokedAt';
export async function GET(r:Request){try{const u=await identity(r);const keys=await db().prepare('SELECT '+fields+' FROM developer_keys k JOIN projects p ON p.id=k.project WHERE k.owner=? AND p.owner=? ORDER BY k.created DESC LIMIT 200').bind(u,u).all();return Response.json({keys:keys.results},{headers})}catch(e){const response=failure(e);response.headers.set('Cache-Control','private, no-store');return response}}
export async function POST(r:Request){try{const u=await identity(r),d=await body(r),project=text(d.project,100,true),label=text(d.label,60,true).trim();await accessProject(project,u,'owner');const policy=await governance(u);if(policy.creationDisabled)throw new HttpError(403,'New API key creation is disabled in your key governance settings.');const now=Date.now(),id=crypto.randomUUID(),key='rc_'+Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),prefix=key.slice(0,11),hash=await keyHash(key),expires=now+policy.maxLifetimeDays*86400000;
 const inserted=await db().prepare('INSERT INTO developer_keys (id,owner,project,label,prefix,hash,created,expires) SELECT ?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM developer_keys WHERE owner=? AND revoked IS NULL AND expires>?)<20 RETURNING id').bind(id,u,project,label,prefix,hash,now,expires,u,now).first();if(!inserted)throw new HttpError(429,'Revoke an unused key before creating another. You can have 20 active keys.');await activity(project,u,'Created a read-only project API key.').run();const record=await db().prepare('SELECT '+fields+' FROM developer_keys k JOIN projects p ON p.id=k.project WHERE k.id=?').bind(id).first();return Response.json({key,record},{status:201,headers})}catch(e){const response=failure(e);response.headers.set('Cache-Control','private, no-store');return response}}
export async function DELETE(r:Request){try{const u=await identity(r),d=await body(r),id=text(d.id,100,true),k=await db().prepare('SELECT project FROM developer_keys WHERE id=? AND owner=?').bind(id,u).first();if(!k)throw new HttpError(404,'Key not found.');await accessProject(String(k.project),u,'owner');await db().batch([db().prepare('UPDATE developer_keys SET revoked=COALESCE(revoked,?) WHERE id=? AND owner=?').bind(Date.now(),id,u),activity(String(k.project),u,'Revoked a project API key.')]);return Response.json({ok:true},{headers})}catch(e){const response=failure(e);response.headers.set('Cache-Control','private, no-store');return response}}
