import {reserveMonthlyRequest} from '../../lib/usage-controls';
import {requireProjectFeature} from '../../lib/project-policy';
import {env} from "cloudflare:workers";
import {identity,db,failure,body,text,accessProject,HttpError} from "../shared";
import {boundedHistory,readDeltas,type ModelMessage} from "@/lib/model";
export async function POST(r:Request){try{
 const owner=await identity(r),e=env as unknown as Record<string,string>,d=await body(r);
 if(!e.AI_BASE_URL||!e.AI_MODEL||!e.AI_API_KEY)throw new HttpError(503,"AI replies aren’t connected yet. You can still create projects and edit documents.");
 const content=text(d.content,20000,true).trim(),id=text(d.id,100,true),requestId=text(d.requestId,100,true),project=d.project?await accessProject(text(d.project,100,true),owner):null;
 if(project)await requireProjectFeature(String(project.id),'aiEnabled');
 const existing=await db().prepare("SELECT * FROM conversations WHERE id=?").bind(id).first();if(existing&&existing.owner!==owner)throw new HttpError(404,"Conversation not found.");if(existing&&(existing.project??null)!==(d.project??null))throw new HttpError(400,"Conversation belongs to another project.");
 const priorRequest=await db().prepare("SELECT id FROM messages WHERE id=?").bind(requestId).first();if(priorRequest)throw new HttpError(409,"This message was already submitted. Reopen the conversation to see its saved reply.");
await reserveMonthlyRequest(owner); const daily=Math.max(1,Math.min(Number(e.AI_DAILY_REQUEST_LIMIT)||50,1000)),global=Math.max(1,Math.min(Number(e.AI_DAILY_SITE_REQUEST_LIMIT)||200,10000)),day=new Date().toISOString().slice(0,10);
 for(const [key,limit] of [[owner+":"+day,daily],["site:"+day,global]] as const){const reservation=await db().prepare("INSERT INTO quotas (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count<? RETURNING count").bind(key,limit).first();if(!reservation)throw new HttpError(429,"Today’s usage limit has been reached. Your draft is safe; try again tomorrow.");}
 const rows=existing?(await db().prepare("SELECT role,content FROM (SELECT role,content,created,rowid AS seq FROM messages WHERE conversation=? ORDER BY created DESC,rowid DESC LIMIT 30) ORDER BY created,seq").bind(id).all()).results as ModelMessage[]:[];
 const context=project?"\nProject goal: "+project.goal+"\nReference context (user supplied): "+project.context:"";
 const base=new URL(e.AI_BASE_URL);if(base.protocol!=="https:")throw new HttpError(503,"The model connection needs a secure HTTPS endpoint.");
 let upstream:Response;try{upstream=await fetch(base.toString().replace(/\/$/,"")+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${e.AI_API_KEY}`},body:JSON.stringify({model:e.AI_MODEL,messages:[{role:"system",content:"You are Recoord. Help users turn ideas into useful plans, drafts, and decisions. Ask only necessary clarifying questions. Distinguish facts, assumptions, and suggestions. You cannot take external actions. Use Markdown."},{role:"user",content:"Project context for this conversation:"+context},...boundedHistory(rows),{role:"user",content}],stream:true,max_tokens:Math.max(256,Math.min(Number(e.AI_MAX_OUTPUT_TOKENS)||2048,4096))}),signal:AbortSignal.timeout(90000)})}catch{throw new HttpError(502,"The model provider didn’t respond. Your draft has been kept; please retry.")}
 if(!upstream.ok||!upstream.body)throw new HttpError(502,"The model provider couldn’t answer. Your draft has been kept; please try later.");
 const now=Date.now();await db().batch([db().prepare("INSERT INTO conversations (id,owner,project,title,updated) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET updated=excluded.updated").bind(id,owner,d.project||null,content.slice(0,70),now),db().prepare("INSERT INTO messages (id,conversation,role,content,created) VALUES (?,?,?,?,?)").bind(requestId,id,"user",content,now),db().prepare("DELETE FROM drafts WHERE id=? AND owner=?").bind(owner+":"+(d.draftScope||id),owner)]);
 const encoder=new TextEncoder();let disconnected=false;const stream=new ReadableStream<Uint8Array>({cancel(){disconnected=true},async start(controller){let answer="";const send=(v:object)=>{if(!disconnected)try{controller.enqueue(encoder.encode(JSON.stringify(v)+"\n"))}catch{disconnected=true}};try{send({id});for await(const delta of readDeltas(upstream.body!)){answer+=delta;send({delta});if(answer.length>100000)throw new Error("Reply limit")}if(!answer)throw new Error("Empty reply");await db().prepare("INSERT INTO messages (id,conversation,role,content,created) SELECT ?,id,'assistant',?,? FROM conversations WHERE id=? AND owner=?").bind(requestId+":reply",answer,Date.now(),id,owner).run();send({done:true})}catch{try{await db().prepare("INSERT INTO messages (id,conversation,role,content,created) SELECT ?,id,'assistant',?,? FROM conversations WHERE id=? AND owner=?").bind(requestId+":reply",(answer||"No answer was received.")+"\n\n[Incomplete reply — generation was interrupted.]",Date.now(),id,owner).run()}catch{}send({error:"The reply was interrupted. Any partial reply is marked incomplete. Reopen the conversation to check it."})}finally{if(!disconnected)controller.close()}}});return new Response(stream,{headers:{"Content-Type":"application/x-ndjson","Cache-Control":"no-store"}})
 }catch(e){return failure(e)}}
