import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {build} from 'esbuild';import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';
test('Groq tools validate models and uploads, enforce identity/project/quota, and keep content out of storage',async()=>{
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile('drizzle/'+f,'utf8'));
 const DB={prepare(q){return {bind(...args){const s=sql.prepare(q);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)}}}}}};
 globalThis.__aiEnv={DB,AI_BASE_URL:'https://api.groq.com/openai/v1',AI_API_KEY:'PRIVATE_KEY',AI_MODEL:'openai/gpt-oss-120b'};const realFetch=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'recoord-ai-tools-'));let calls=[];
 try{
 const routes={};for(const [name,path] of [['tools','app/api/ai-tools/route.ts'],['models','app/api/ai-models/route.ts'],['helper','app/lib/ai-requests.ts']]){const outfile=join(dir,name+'.mjs');await build({entryPoints:[resolve(path)],outfile,bundle:true,format:'esm',platform:'node',plugins:[{name:'test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='env'?'export const env=globalThis.__aiEnv':'export async function getChatGPTUser(){return globalThis.__aiUser}',loader:'js'}));}}]});routes[name]=await import(pathToFileURL(outfile));}
 const login=u=>globalThis.__aiUser=u?{userId:u,email:u+'@example.test',displayName:u}:null;
 async function request(values,user='alice',origin='https://recoord.test'){login(user);const f=new FormData();for(const [k,v] of Object.entries(values))f.set(k,v);return routes.tools.POST(new Request('https://recoord.test/api/ai-tools',{method:'POST',headers:{origin},body:f}));}
 const speech={task:'speech',model:'canopylabs/orpheus-v1-english',voice:'troy',text:'PRIVATE_TEXT'};
 globalThis.fetch=async(url,options)=>{calls.push({url,options});if(url.endsWith('/audio/speech'))return new Response(new TextEncoder().encode('RIFF0000WAVEtest'),{headers:{'Content-Type':'audio/wav'}});if(url.endsWith('/audio/transcriptions'))return Response.json({text:'PRIVATE_TRANSCRIPT'});return Response.json({choices:[{message:{content:'PRIVATE_ANALYSIS'}}]});};
 assert.equal((await request(speech,null)).status,401);assert.equal((await request(speech,'alice','https://evil.test')).status,403);
 assert.equal((await request({...speech,model:'evil'})).status,400);assert.equal((await request({...speech,voice:'noura'})).status,400);assert.equal((await request({...speech,text:'x'.repeat(201)})).status,400);assert.equal(calls.length,0);
 let r=await request(speech);assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'audio/wav');assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.equal(calls[0].url,'https://api.groq.com/openai/v1/audio/speech');assert.equal(JSON.parse(calls[0].options.body).voice,'troy');
 r=await request({...speech,model:'canopylabs/orpheus-arabic-saudi',voice:'noura'});assert.equal(r.status,200);
 const transcription={task:'transcription',model:'whisper-large-v3',file:new File(['test'],'test.wav',{type:'audio/wav'})};r=await request(transcription);assert.equal(r.status,200);assert.equal((await r.json()).text,'PRIVATE_TRANSCRIPT');assert.equal(calls.at(-1).options.body.get('model'),'whisper-large-v3');
 assert.equal((await request({...transcription,model:'whisper-large-v3-turbo'})).status,200);assert.equal((await request({...transcription,file:new File(['test'],'test.exe')})).status,400);assert.equal((await request({...transcription,file:new File([new Uint8Array(5*1024*1024+1)],'test.wav')})).status,400);
 const vision={task:'vision',file:new File(['test'],'image.png',{type:'image/png'}),text:'PRIVATE_QUESTION'};r=await request(vision);assert.equal(r.status,200);assert.equal(JSON.parse(calls.at(-1).options.body).model,'qwen/qwen3.8-27b');assert.match(JSON.parse(calls.at(-1).options.body).messages[1].content[1].image_url.url,/^data:image\/png;base64,/);
 assert.equal((await request({...vision,file:new File(['test'],'image.svg',{type:'image/svg+xml'})})).status,400);
 globalThis.fetch=async()=>Response.json({choices:[{message:{content:JSON.stringify({flagged:false,category:'none',explanation:'No issue detected.'})}}]});r=await request({task:'safety',text:'Hello'});assert.equal(r.status,200);assert.equal((await r.json()).flagged,false);
 globalThis.fetch=async()=>Response.json({choices:[{message:{content:'bad JSON'}}]});assert.equal((await request({task:'safety',text:'Hello'})).status,502);
 sql.prepare("INSERT INTO projects VALUES ('p','bob','P','','',1)").run();assert.equal((await request({...speech,project:'p'})).status,404);sql.prepare("INSERT INTO members VALUES ('m','p','alice','viewer')").run();sql.prepare('INSERT INTO project_policies VALUES (?,?,?,?,?)').run('p',JSON.stringify({usageVisibility:'members',logsVisibility:'members',aiEnabled:false,importsEnabled:true,fileSearchEnabled:true,apiEnabled:true,auditEnabled:false,apiLogMode:'disabled',inviteDomains:[]}),1,'change',1);assert.equal((await request({...speech,project:'p'})).status,403);
 globalThis.fetch=async()=>new Response('PRIVATE_PROVIDER_ERROR',{status:403});r=await request(speech);assert.equal(r.status,502);assert(!(await r.text()).includes('PRIVATE'));
 globalThis.fetch=async()=>Response.json({error:{code:'model_terms_required',message:'PRIVATE'}},{status:400});r=await request(speech);assert.match(await r.text(),/Accept this model/);
 assert(!JSON.stringify(sql.prepare('SELECT * FROM request_metrics').all()).includes('PRIVATE'));assert.equal(sql.prepare('SELECT COUNT(*) n FROM messages').get().n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM documents').get().n,0);
 login('alice');r=await routes.models.GET(new Request('https://recoord.test/api/ai-models'));const models=await r.json();assert.equal(models.models.length,3);assert(!JSON.stringify(models).includes('PRIVATE'));
 const {chooseChatModel,boundedBytes}=routes.helper;assert.equal(chooseChatModel('qwen/qwen3.8-27b',globalThis.__aiEnv),'qwen/qwen3.8-27b');assert.throws(()=>chooseChatModel('not-allowed',globalThis.__aiEnv));assert.throws(()=>chooseChatModel('qwen/qwen3.8-27b',{AI_BASE_URL:'https://other.test',AI_MODEL:'default'}));assert.equal(chooseChatModel(undefined,{AI_MODEL:'default'}),'default');
 await assert.rejects(boundedBytes(new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(11));c.close()}})),10));
 sql.prepare('INSERT INTO usage_preferences VALUES (?,?,?,?,?)').run('alice',1,80,1,1);assert.equal((await request(speech)).status,429);
 globalThis.__aiEnv.AI_BASE_URL='https://evil.test';assert.equal((await request(speech)).status,503);
 }finally{globalThis.fetch=realFetch;sql.close();await rm(dir,{recursive:true,force:true});delete globalThis.__aiEnv;delete globalThis.__aiUser;}
});
