import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {build} from 'esbuild';import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';
test('project groups enforce owner management and current membership without granting permissions',async()=>{
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile('drizzle/'+f,'utf8'));
 const DB={prepare(q){return {bind(...args){const s=sql.prepare(q);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)},query:q,args}}}},async batch(statements){sql.exec('BEGIN');try{const results=statements.map(s=>({results:sql.prepare(s.query).all(...s.args)}));sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};globalThis.__groupsEnv={DB};const dir=await mkdtemp(join(tmpdir(),'recoord-groups-'));
 try{const outfile=join(dir,'route.mjs');await build({entryPoints:[resolve('app/api/groups/route.ts')],outfile,bundle:true,format:'esm',platform:'node',plugins:[{name:'test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='env'?'export const env=globalThis.__groupsEnv':'export async function getChatGPTUser(){return globalThis.__groupsUser}',loader:'js'}));}}]});const route=await import(pathToFileURL(outfile));
 async function req(user,method='GET',data,project='p',origin='https://recoord.test'){globalThis.__groupsUser=user?{userId:user,email:user+'@example.test',displayName:user}:null;const r=await route[method](new Request('https://recoord.test/api/groups?project='+project,{method,headers:{origin},body:method==='GET'?undefined:JSON.stringify({project,...data})}));return {status:r.status,data:await r.json(),headers:r.headers};}
 assert.equal((await req(null)).status,401);for(const user of ['owner','member','outsider'])sql.prepare('INSERT INTO profiles VALUES (?,?,?)').run(user,user+'@example.test',user);sql.prepare("INSERT INTO projects VALUES ('p','owner','Project','','',1),('q','outsider','Other','','',1)").run();sql.prepare("INSERT INTO members VALUES ('m','p','member','viewer')").run();
 const input={name:'Design',description:'Design collaborators',memberIds:['member','owner','member']};
 assert.equal((await req('outsider')).status,404);assert.equal((await req('member','POST',input)).status,403);assert.equal((await req('owner','POST',input,'p','https://evil.test')).status,403);
 assert.equal((await req('owner','POST',{...input,memberIds:['outsider']})).status,400);assert.equal((await req('owner','POST',{...input,memberIds:Array(101).fill('owner')})).status,400);assert.equal((await req('owner','POST',{...input,name:' '})).status,400);
 let r=await req('owner','POST',input);assert.equal(r.status,201);assert.equal(r.headers.get('Cache-Control'),'private, no-store');const group=r.data.groups[0];assert.deepEqual(group.memberIds,['member','owner']);assert.equal((await req('member')).data.role,'viewer');assert.equal((await req('member')).data.groups.length,1);
 assert.equal((await req('owner','POST',{...input,name:' design '})).status,409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM project_groups').get().n,1);
 const other=(await req('outsider','POST',{name:'Other team',memberIds:['outsider']},'q')).data.groups[0];assert.equal((await req('owner','PATCH',{...input,id:other.id})).status,404);assert.equal((await req('owner','DELETE',{id:other.id})).status,404);
 assert.equal((await req('member','PATCH',{...input,id:group.id})).status,403);assert.equal((await req('member','DELETE',{id:group.id})).status,403);
 r=await req('owner','PATCH',{id:group.id,name:'Product',description:'Updated',memberIds:['member']});assert.equal(r.status,200);assert.deepEqual(r.data.groups[0].memberIds,['member']);assert.equal(sql.prepare("SELECT role FROM members WHERE user='member'").get().role,'viewer');
 const second=(await req('owner','POST',{name:'Research',memberIds:['owner']})).data.groups.find(g=>g.name==='Research');r=await req('owner','PATCH',{id:group.id,name:'RESEARCH',memberIds:['owner']});assert.equal(r.status,409);assert.deepEqual((await req('owner')).data.groups.find(g=>g.id===group.id).memberIds,['member']);
 sql.prepare("DELETE FROM members WHERE user='member'").run();assert.deepEqual((await req('owner')).data.groups.find(g=>g.id===group.id).memberIds,[]);assert.equal((await req('member')).status,404);assert.equal((await req('owner','PATCH',{...input,id:group.id})).status,400);
 assert.equal((await req('owner','DELETE',{id:group.id})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM group_members WHERE group_id=?').get(group.id).n,0);
 for(let n=0;n<49;n++)sql.prepare('INSERT INTO project_groups VALUES (?,?,?,?,?,?,?)').run('limit'+n,'p','Team '+n,'team '+n,'',1,1);assert.equal((await req('owner','POST',{name:'Over cap',memberIds:['owner']})).status,429);assert.equal(sql.prepare("SELECT COUNT(*) n FROM project_groups WHERE project='p'").get().n,50);
 sql.prepare("INSERT INTO usage_preferences(owner,updated) VALUES ('owner',1)").run();assert.equal(sql.prepare("SELECT monthly_limit FROM usage_preferences WHERE owner='owner'").get().monthly_limit,1000);
 sql.prepare("DELETE FROM projects WHERE id='p'").run();assert.equal(sql.prepare('SELECT COUNT(*) n FROM group_members WHERE group_id=?').get(second.id).n,0);sql.prepare("DELETE FROM profiles WHERE id='owner'").run();assert.equal(sql.prepare('SELECT COUNT(*) n FROM usage_preferences').get().n,0);
 }finally{sql.close();await rm(dir,{recursive:true,force:true});delete globalThis.__groupsEnv;delete globalThis.__groupsUser;}
});
