import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {build} from 'esbuild';import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';
test('project policy enforces owner edits, revision conflicts, exact invitation domains and private metadata visibility',async()=>{
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile('drizzle/'+f,'utf8'));
 const DB={prepare(q){return {bind(...args){const s=sql.prepare(q);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)},query:q,args}}}},async batch(statements){sql.exec('BEGIN');try{const results=statements.map(s=>({results:sql.prepare(s.query).all(...s.args)}));sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};globalThis.__policyEnv={DB};const dir=await mkdtemp(join(tmpdir(),'recoord-policy-'));
 try{const plugin={name:'test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='env'?'export const env=globalThis.__policyEnv':'export async function getChatGPTUser(){return globalThis.__policyUser}',loader:'js'}));}};
 for(const [name,file] of [['route','app/api/project-policy/route.ts'],['helpers','app/lib/project-policy.ts']])await build({entryPoints:[resolve(file)],outfile:join(dir,name+'.mjs'),bundle:true,format:'esm',platform:'node',plugins:[plugin]});const route=await import(pathToFileURL(join(dir,'route.mjs'))),helpers=await import(pathToFileURL(join(dir,'helpers.mjs')));
 async function req(user,method='GET',policy,origin='https://recoord.test'){globalThis.__policyUser=user?{userId:user,email:user+'@example.test',displayName:user}:null;const r=await route[method](new Request('https://recoord.test/api/project-policy?project=p',{method,headers:{origin},body:method==='PATCH'?JSON.stringify({project:'p',policy}):undefined}));return {status:r.status,data:await r.json()};}
 assert.equal((await req(null)).status,401);for(const user of ['owner','member','outsider'])sql.prepare('INSERT INTO profiles VALUES (?,?,?)').run(user,user+'@example.test',user);sql.prepare("INSERT INTO projects VALUES ('p','owner','Project','','',1)").run();sql.prepare("INSERT INTO members VALUES ('m','p','member','editor')").run();
 assert.equal((await req('outsider')).status,404);let p=(await req('owner')).data.policy;assert.equal(p.revision,0);assert.equal(p.apiEnabled,true);assert.deepEqual(p.inviteDomains,[]);
 assert.equal((await req('member','PATCH',p)).status,403);assert.equal((await req('owner','PATCH',p,'https://evil.test')).status,403);
 for(const domain of ['https://example.com','*.example.com','-bad.com','bad..com','user@example.com'])assert.equal((await req('owner','PATCH',{...p,inviteDomains:[domain]})).status,400);
 let response=await req('owner','PATCH',{...p,auditEnabled:true,apiEnabled:false,usageVisibility:'owner',logsVisibility:'owner',inviteDomains:[' EXAMPLE.com ','example.com']});assert.equal(response.status,200);p=response.data.policy;assert.equal(p.revision,1);assert.deepEqual(p.inviteDomains,['example.com']);assert.equal(response.data.events.length,1);assert(response.data.events[0].details.changedFields.includes('auditEnabled'));
 assert.equal((await req('owner','PATCH',{...p,revision:0})).status,409);assert.equal((await req('owner')).data.events.length,1);
 await assert.rejects(helpers.requireProjectFeature('p','apiEnabled'),e=>e.status===403);await helpers.assertInviteDomain('p','USER@example.com');await assert.rejects(helpers.assertInviteDomain('p','a@sub.example.com'),e=>e.status===403);
 await helpers.recordProjectApiRead('p');await helpers.recordProjectApiRead('p');assert.equal((await req('owner')).data.usage.reads,2);assert.equal((await req('member')).data.usage,null);assert.equal((await req('member')).data.events.length,0);
 response=await req('owner','PATCH',{...p,auditEnabled:false,apiLogMode:'per_call',logsVisibility:'members',usageVisibility:'members'});p=response.data.policy;assert.equal(response.data.events.length,2);
 await helpers.logProjectEvent('p','owner','api.read',{status:200,keyId:'safe-key',authorization:'secret'});assert.equal((await req('owner')).data.events.length,2);
 await helpers.logProjectEvent('p','owner','api.read',{requested:true,status:200,keyId:'safe-key',authorization:'secret',body:'PRIVATE'});let events=(await req('member')).data.events;assert.equal(events.length,3);const api=events.find(e=>e.action==='api.read');assert.deepEqual(api.details,{status:200,keyId:'safe-key'});assert.equal((await req('member')).data.usage.reads,2);
 response=await req('owner','PATCH',{...p,logsVisibility:'hidden'});p=response.data.policy;assert.equal(response.data.events.length,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM project_policy_events').get().n,3);
 // Audit disabled on both sides does not create policy-change events.
 assert.equal((await req('member')).data.events.length,0);sql.prepare("DELETE FROM projects WHERE id='p'").run();for(const table of ['project_policies','project_api_usage','project_policy_events'])assert.equal(sql.prepare('SELECT COUNT(*) n FROM '+table).get().n,0);
 }finally{sql.close();await rm(dir,{recursive:true,force:true});delete globalThis.__policyEnv;delete globalThis.__policyUser;}
});
