import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {build} from 'esbuild';import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';
test('request analytics stores bounded metadata, isolates users and filters real outcomes; chat records completed and interrupted streams',async()=>{
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile('drizzle/'+f,'utf8'));
 const DB={prepare(q){return {bind(...args){const s=sql.prepare(q);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)},query:q,args}}}},async batch(statements){sql.exec('BEGIN');try{const results=statements.map(s=>({results:sql.prepare(s.query).all(...s.args)}));sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};globalThis.__metricEnv={DB,AI_BASE_URL:'https://model.test/v1',AI_API_KEY:'PRIVATE_KEY',AI_MODEL:'mock'};const dir=await mkdtemp(join(tmpdir(),'recoord-metrics-')),realFetch=globalThis.fetch;
 try{const routes={};for(const [name,file] of [['history','app/api/usage-history/route.ts'],['helper','app/lib/request-metrics.ts'],['chat','app/api/chat/route.ts'],['summary','app/api/summary/route.ts'],['search','app/api/project-search/route.ts']]){const outfile=join(dir,name+'.mjs');await build({entryPoints:[resolve(file)],outfile,bundle:true,format:'esm',platform:'node',plugins:[{name:'test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='env'?'export const env=globalThis.__metricEnv':'export async function getChatGPTUser(){return globalThis.__metricUser}',loader:'js'}));}}]});routes[name]=await import(pathToFileURL(outfile));}
 const login=user=>{globalThis.__metricUser=user?{userId:user,email:user+'@example.test',displayName:user}:null};async function history(user,query=''){login(user);const response=await routes.history.GET(new Request('https://recoord.test/api/usage-history'+query));return {status:response.status,data:await response.json()};}
 assert.equal((await history(null)).status,401);for(const u of ['alice','bob'])sql.prepare('INSERT INTO profiles VALUES (?,?,?)').run(u,u+'@example.test',u);sql.prepare("INSERT INTO projects VALUES ('p','alice','P','','',1),('q','bob','Q','','',1)").run();sql.prepare("INSERT INTO members VALUES ('member','p','bob','viewer')").run();
 for(const [id,owner,project] of [['ka','alice','p'],['kb','bob','q']])sql.prepare('INSERT INTO developer_keys (id,owner,project,label,prefix,hash,created,expires) VALUES (?,?,?,?,?,?,?,?)').run(id,owner,project,'key','prefix',id,1,Date.now()+100000);
 const {recordMetric}=routes.helper;await recordMetric({owner:'alice',project:'p',keyId:'ka',source:'project_api',status:200,duration:100,content:'PRIVATE_BODY',token:'PRIVATE_KEY'});await recordMetric({owner:'alice',project:'p',source:'chat',status:502,duration:300});await recordMetric({owner:'bob',project:'p',source:'chat',status:200,duration:999});
 await recordMetric({owner:'alice',source:'invalid',status:200,duration:1});await recordMetric({owner:'alice',source:'chat',status:200,duration:-1});await recordMetric({owner:'alice',source:'chat',status:Infinity,duration:1});assert.equal(sql.prepare('SELECT COUNT(*) n FROM request_metrics').get().n,3);
 let response=await history('alice','?days=7');assert.deepEqual(response.data.totals,{requests:2,successes:1,errors:1,averageDurationMs:200});assert.equal(response.data.daily.length,7);assert.equal(response.data.daily.reduce((n,d)=>n+d.requests,0),2);assert.equal(response.data.recentFailures[0].status,502);assert(!JSON.stringify(response.data).includes('PRIVATE'));assert.equal(response.data.sources.length,2);
 assert.equal((await history('alice','?source=project_api&key=ka')).data.totals.requests,1);assert.equal((await history('bob','?project=p')).data.totals.requests,1);assert.equal((await history('alice','?key=kb')).status,404);assert.equal((await history('alice','?project=q')).status,404);assert.equal((await history('alice','?days=8')).status,400);assert.equal((await history('alice','?source=bad')).status,400);
 const old=Date.now()-95*86400000;sql.prepare('INSERT INTO request_metrics VALUES (?,?,?,?,?,?,?,?)').run('old','alice',null,null,'summary',200,50,old);response=await history('alice','?days=90');assert.equal(response.data.since,old);assert.equal(response.data.totals.requests,2);
 // Provider outcomes, including stream interruptions, contain no prompt or response text.
 login('alice');async function chat(){const r=await routes.chat.POST(new Request('https://recoord.test/api/chat',{method:'POST',headers:{origin:'https://recoord.test'},body:JSON.stringify({id:crypto.randomUUID(),requestId:crypto.randomUUID(),content:'PRIVATE_PROMPT',project:'p'})}));await r.text();return r.status;}
 globalThis.fetch=async()=>new Response('data: {"choices":[{"delta":{"content":"PRIVATE_REPLY"}}]}\n\ndata: [DONE]\n');assert.equal(await chat(),200);
 globalThis.fetch=async()=>new Response('data: {"choices":[{"delta":{"content":"PARTIAL_PRIVATE"}}]}\n');assert.equal(await chat(),200);
 globalThis.fetch=async()=>new Response('provider failure',{status:503});assert.equal(await chat(),502);
 const chatRows=sql.prepare("SELECT status FROM request_metrics WHERE owner='alice' AND source='chat' ORDER BY created,id").all();assert.equal(chatRows.filter(r=>r.status===200).length,1);assert.equal(chatRows.filter(r=>r.status===502).length,3);
 globalThis.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'Done',suggestions:[]})}}]}));const summary=await routes.summary.POST(new Request('https://recoord.test/api/summary',{method:'POST',headers:{origin:'https://recoord.test'},body:JSON.stringify({project:'p'})}));assert.equal(summary.status,200);
 const search=await routes.search.GET(new Request('https://recoord.test/api/project-search?project=p&q=test'));assert.equal(search.status,200);assert.equal(sql.prepare("SELECT COUNT(*) n FROM request_metrics WHERE source='file_search'").get().n,1);
 const priorCount=sql.prepare('SELECT COUNT(*) n FROM request_metrics').get().n;sql.prepare('INSERT INTO project_policies VALUES (?,?,?,?,?)').run('p',JSON.stringify({usageVisibility:'members',logsVisibility:'members',aiEnabled:false,importsEnabled:true,fileSearchEnabled:true,apiEnabled:true,auditEnabled:false,apiLogMode:'disabled',inviteDomains:[]}),1,'test-change',1);assert.equal(await chat(),403);assert.equal(sql.prepare('SELECT COUNT(*) n FROM request_metrics').get().n,priorCount);
 assert(!JSON.stringify(sql.prepare('SELECT * FROM request_metrics').all()).includes('PRIVATE'));const before=sql.prepare('SELECT COUNT(*) n FROM request_metrics').get().n;globalThis.__metricEnv.DB={prepare(){throw new Error('unavailable')}};await recordMetric({owner:'alice',source:'chat',status:200,duration:2});globalThis.__metricEnv.DB=DB;assert.equal(sql.prepare('SELECT COUNT(*) n FROM request_metrics').get().n,before);
 sql.prepare("DELETE FROM profiles WHERE id='alice'").run();assert.equal(sql.prepare("SELECT COUNT(*) n FROM request_metrics WHERE owner='alice'").get().n,0);
 }finally{globalThis.fetch=realFetch;sql.close();await rm(dir,{recursive:true,force:true});delete globalThis.__metricEnv;delete globalThis.__metricUser;}
});
