import {getChatGPTUser} from '../../chatgpt-auth';
import {identity,db,failure,body,text,HttpError,accessProject} from '../shared';
export const socialJson=(data:unknown)=>Response.json(data,{headers:{'Cache-Control':'private, no-store'}});
export async function socialViewer(){return (await getChatGPTUser())?.userId??''}
export async function socialBlocked(a:string,b:string){return !!a&&!!await db().prepare('SELECT id FROM blocks WHERE (owner=? AND target=?) OR (owner=? AND target=?)').bind(a,b,b,a).first()}
export async function sharingQuota(user:string){const key='sharing:'+user+':'+new Date().toISOString().slice(0,10);if(!await db().prepare('INSERT INTO quotas (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count<100 RETURNING count').bind(key).first())throw new HttpError(429,'You have reached today’s limit of 100 posts and comments. Try again tomorrow.');}
export function sharingId(value:unknown){if(value===undefined)return crypto.randomUUID();const id=text(value,36,true);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw new HttpError(400,'Invalid item ID.');return id}
export async function requireSharedProfile(user:string){const p=await db().prepare('SELECT username,visibility FROM profile_details WHERE id=?').bind(user).first();if(!p?.username||p.visibility!=='members')throw new HttpError(400,'Choose a username and share your profile with members before publishing.');}
const select="SELECT p.id,p.author,p.content,p.image,p.video,p.project_title AS projectTitle,p.work_link AS workLink,p.audience,p.created,u.name,d.username,d.photo FROM posts p JOIN profiles u ON u.id=p.author LEFT JOIN profile_details d ON d.id=p.author";
function visibleSql(){return " (p.author=? OR (d.visibility='members' AND (p.audience='public' OR (?<>'' AND p.audience='connections' AND EXISTS (SELECT 1 FROM connections c WHERE c.status='accepted' AND ((c.sender=? AND c.recipient=p.author) OR (c.recipient=? AND c.sender=p.author))))))) AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.owner=? AND b.target=p.author) OR (b.target=? AND b.owner=p.author))"}
const args=(u:string)=>[u,u,u,u,u,u];
export async function visiblePost(id:string,user:string):Promise<Record<string,unknown>&{canDelete:boolean}>{const post=await db().prepare(select+' WHERE p.id=? AND '+visibleSql()).bind(id,...args(user)).first();if(!post)throw new HttpError(404,'Post not available.');return {...post,canDelete:post.author===user}}
function https(value:unknown){const s=text(value??'',1500).trim();if(s){try{const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password)throw 0}catch{throw new HttpError(400,'Use a full https:// link.')}}return s}
export async function GET(r:Request){try{const u=await socialViewer(),q=new URL(r.url).searchParams,id=q.get('id');if(id)return socialJson({post:await visiblePost(text(id,100,true),u)});const author=text(q.get('author')??'',200);const rows=(await db().prepare(select+' WHERE '+visibleSql()+" AND (?='' OR p.author=?) ORDER BY p.created DESC,p.id DESC LIMIT 30").bind(...args(u),author,author).all()).results;return socialJson({posts:rows.map(p=>({...p,canDelete:p.author===u}))});}catch(e){return failure(e)}}
export async function POST(r:Request){try{
 const u=await identity(r),d=await body(r);await requireSharedProfile(u);
 const id=sharingId(d.id),content=text(d.content??'',4000).trim(),image=text(d.image??'',120000),video=https(d.video),workLink=https(d.workLink),audience=d.audience??'public';
 if(audience!=='public'&&audience!=='connections')throw new HttpError(400,'Choose public or connections visibility.');
 if(image&&!/^data:image\/jpeg;base64,\/9j\/[A-Za-z0-9+/]*={0,2}$/.test(image))throw new HttpError(400,'Choose a supported photo.');
 let projectTitle='';if(d.project){const p=await accessProject(text(d.project,100,true),u,'owner');projectTitle=String(p.title)}
 if(!content&&!image&&!video&&!workLink&&!projectTitle)throw new HttpError(400,'Add some work, a photo, a link, or an update before publishing.');
 const old=await db().prepare('SELECT * FROM posts WHERE id=?').bind(id).first();
 if(old){if(old.author!==u||old.content!==content||old.image!==image||old.video!==video||old.work_link!==workLink||old.project_title!==projectTitle||old.audience!==audience)throw new HttpError(409,'That publication ID has already been used.');return socialJson({post:await visiblePost(id,u)})}
 await sharingQuota(u);await db().prepare('INSERT INTO posts (id,author,content,image,video,project_title,work_link,audience,created) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,u,content,image,video,projectTitle,workLink,audience,Date.now()).run();
 const saved=await visiblePost(id,u);if(saved.author!==u||saved.content!==content||saved.image!==image||saved.video!==video||saved.workLink!==workLink||saved.projectTitle!==projectTitle||saved.audience!==audience)throw new HttpError(409,'That publication ID has already been used.');return socialJson({post:saved});
 }catch(e){return failure(e)}}
export async function DELETE(r:Request){try{const u=await identity(r),d=await body(r),id=text(d.id,100,true);if(!await db().prepare('SELECT id FROM posts WHERE id=? AND author=?').bind(id,u).first())throw new HttpError(404,'Post not available.');await db().batch([db().prepare("DELETE FROM social_comments WHERE target_type='post' AND target=? AND EXISTS (SELECT 1 FROM posts WHERE id=? AND author=?)").bind(id,id,u),db().prepare('DELETE FROM posts WHERE id=? AND author=?').bind(id,u)]);return socialJson({ok:true})}catch(e){return failure(e)}}
