import {identity,db,failure,body,text,accessProject,activity,HttpError} from '../shared';
export async function GET(r:Request){try{const u=await identity(r),p=new URL(r.url).searchParams.get('project');if(!p){const invites=await db().prepare('SELECT i.*,p.title FROM invitations i JOIN projects p ON p.id=i.project JOIN profiles u ON lower(u.email)=i.email WHERE u.id=? AND i.created>? AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.owner=u.id AND b.target=p.owner) OR (b.target=u.id AND b.owner=p.owner))').bind(u,Date.now()-7*86400000).all();return Response.json({invitations:invites.results},{headers:{'Cache-Control':'no-store'}})}const project=await accessProject(p,u);const [members,tasks,comments,decisions,activities,documents,invitations]=await db().batch([db().prepare("SELECT u.id,u.name,u.email,'owner' AS role FROM profiles u WHERE u.id=? UNION ALL SELECT u.id,u.name,u.email,m.role FROM members m JOIN profiles u ON u.id=m.user WHERE m.project=?").bind(project.owner,p),db().prepare('SELECT * FROM tasks WHERE project=? ORDER BY updated DESC').bind(p),db().prepare('SELECT c.*,u.name AS authorName FROM comments c LEFT JOIN profiles u ON u.id=c.author WHERE c.project=? ORDER BY c.created DESC LIMIT 200').bind(p),db().prepare('SELECT d.*,u.name AS authorName FROM decisions d LEFT JOIN profiles u ON u.id=d.author WHERE d.project=? ORDER BY d.created DESC LIMIT 200').bind(p),db().prepare('SELECT a.*,u.name AS actorName FROM activities a LEFT JOIN profiles u ON u.id=a.actor WHERE a.project=? ORDER BY a.created DESC LIMIT 100').bind(p),db().prepare('SELECT id,title FROM documents WHERE project=?').bind(p),db().prepare('SELECT * FROM invitations WHERE project=? AND ?=\'owner\' ORDER BY created DESC').bind(p,project.role)]);return Response.json({role:project.role,members:members.results,tasks:tasks.results,comments:comments.results,decisions:decisions.results,activities:activities.results,documents:documents.results,invitations:invitations.results},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(r:Request){try{const u=await identity(r),d=await body(r),action=text(d.action,30,true);
 if(action==='accept'||action==='decline'){const id=text(d.id,100,true),invite=await db().prepare('SELECT i.* FROM invitations i JOIN projects p ON p.id=i.project JOIN profiles u ON lower(u.email)=i.email WHERE i.id=? AND u.id=? AND i.created>? AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.owner=u.id AND b.target=p.owner) OR (b.target=u.id AND b.owner=p.owner))').bind(id,u,Date.now()-7*86400000).first();if(!invite)throw new HttpError(404,'Invitation not found or expired. Sign in with the invited email.');if(action==='decline'){await db().prepare('DELETE FROM invitations WHERE id=?').bind(id).run();return Response.json({ok:true})}await db().batch([db().prepare('INSERT INTO members (id,project,user,role) SELECT ?,project,?,role FROM invitations WHERE id=? ON CONFLICT(id) DO NOTHING').bind(invite.project+':'+u,u,id),db().prepare('DELETE FROM invitations WHERE id=?').bind(id),activity(String(invite.project),u,'Joined the project.')]);return Response.json({project:invite.project})}
 const p=text(d.project,100,true);await accessProject(p,u,['invite','revoke','role','remove'].includes(action)?'owner':'write');
 if(action==='invite'){const email=text(d.email,254,true).trim().toLowerCase(),role=d.role;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!['editor','viewer'].includes(role))throw new HttpError(400,'Enter a valid email and role.');if(await db().prepare('SELECT b.id FROM blocks b JOIN profiles t ON lower(t.email)=? WHERE (b.owner=? AND b.target=t.id) OR (b.target=? AND b.owner=t.id)').bind(email,u,u).first())throw new HttpError(404,'Person not available.');const exists=await db().prepare('SELECT u.id FROM profiles u WHERE lower(u.email)=? AND (u.id=(SELECT owner FROM projects WHERE id=?) OR u.id IN (SELECT user FROM members WHERE project=?))').bind(email,p,p).first();if(exists)throw new HttpError(409,'This person is already a member.');const id=crypto.randomUUID();await db().batch([db().prepare('DELETE FROM invitations WHERE project=? AND email=?').bind(p,email),db().prepare('INSERT INTO invitations (id,project,email,role,created) VALUES (?,?,?,?,?)').bind(id,p,email,role,Date.now()),activity(p,u,'Created an invitation with '+role+' access.')]);return Response.json({id})}
 if(action==='revoke'){await db().batch([db().prepare('DELETE FROM invitations WHERE id=? AND project=?').bind(text(d.id,100,true),p),activity(p,u,'Revoked an invitation.')])}
 else if(action==='role'||action==='remove'){const member=text(d.user,150,true);if(action==='role'){if(!['viewer','editor'].includes(d.role))throw new HttpError(400,'Invalid role.');await db().batch([db().prepare('UPDATE members SET role=? WHERE project=? AND user=?').bind(d.role,p,member),activity(p,u,'Changed a member role to '+d.role+'.')])}else await db().batch([db().prepare('UPDATE tasks SET assignee=NULL,version=version+1 WHERE project=? AND assignee=?').bind(p,member),db().prepare('DELETE FROM members WHERE project=? AND user=?').bind(p,member),activity(p,u,'Removed a member from the project.')])}
 else if(action==='task'){const title=text(d.title,200,true),id=d.id?text(d.id,100,true):crypto.randomUUID(),assignee=d.assignee?text(d.assignee,150,true):null,due=d.due?text(d.due,10,true):null,status=d.status||'todo';if(!['todo','doing','done'].includes(status))throw new HttpError(400,'Invalid status.');if(due&&(!/^\d{4}-\d{2}-\d{2}$/.test(due)||isNaN(Date.parse(due))||new Date(due).toISOString().slice(0,10)!==due))throw new HttpError(400,'Choose a valid date.');if(assignee)await accessProject(p,assignee);if(d.id){if(!Number.isInteger(d.version))throw new HttpError(400,'Missing task version.');const saved=await db().prepare('UPDATE tasks SET title=?,assignee=?,due=?,status=?,version=version+1,updated=? WHERE id=? AND project=? AND version=? RETURNING id').bind(title,assignee,due,status,Date.now(),id,p,d.version).first();if(!saved)throw new HttpError(409,'This task changed. Refresh before editing it again.')}else await db().prepare('INSERT INTO tasks (id,project,title,assignee,due,status,version,updated) VALUES (?,?,?,?,?,?,1,?)').bind(id,p,title,assignee,due,status,Date.now()).run();await activity(p,u,(d.id?'Updated task: ':'Added task: ')+title).run()}
 else if(action==='deleteTask'){await db().batch([db().prepare('DELETE FROM tasks WHERE id=? AND project=?').bind(text(d.id,100,true),p),activity(p,u,'Deleted a task.')])}
 else if(action==='comment'){const content=text(d.content,5000,true),document=d.document?text(d.document,100,true):null; if(document&&!await db().prepare('SELECT id FROM documents WHERE id=? AND project=?').bind(document,p).first())throw new HttpError(404,'Document not found.');const mentions=Array.isArray(d.mentions)?[...new Set(d.mentions)].slice(0,20):[];for(const id of mentions)await accessProject(p,text(id,150,true));await db().batch([db().prepare('INSERT INTO comments (id,project,document,author,content,mentions,created) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),p,document,u,content,JSON.stringify(mentions),Date.now()),activity(p,u,'Posted a comment'+(mentions.length?' with mentions.':'.'))])}
 else if(action==='decision'){await db().batch([db().prepare('INSERT INTO decisions (id,project,author,content,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),p,u,text(d.content,10000,true),Date.now()),activity(p,u,'Recorded a decision.')])}
 else if(action==='update'){await activity(p,u,text(d.content,10000,true)).run()}
 else throw new HttpError(400,'Unknown action.');return Response.json({ok:true})
}catch(e){return failure(e)}}
