import {identity,db,failure,body,text,accessProject,HttpError} from '../shared';
import {getProjectPolicy,validatePolicy,policyFields,type ProjectPolicy} from '../../lib/project-policy';
const headers={'Cache-Control':'private, no-store'};
async function result(project:string,role:string,policy?:ProjectPolicy){policy??=await getProjectPolicy(project);const visible=policy.logsVisibility==='members'||policy.logsVisibility==='owner'&&role==='owner';const events=visible?(await db().prepare('SELECT e.id,e.actor,COALESCE(p.name,\'Former member\') AS actorName,e.action,e.details,e.created FROM project_policy_events e LEFT JOIN profiles p ON p.id=e.actor WHERE e.project=? ORDER BY e.created DESC,e.id DESC LIMIT 100').bind(project).all()).results.map(e=>({...e,details:JSON.parse(String(e.details))})):[];const day=new Date().toISOString().slice(0,10),usage=policy.usageVisibility==='members'||role==='owner'?{day,reads:Number((await db().prepare('SELECT count FROM project_api_usage WHERE project=? AND day=?').bind(project,day).first<{count:number}>())?.count??0)}:null;return {policy,events,usage,role};}
function fail(error:unknown){const response=failure(error);response.headers.set('Cache-Control','private, no-store');return response;}
export async function GET(r:Request){try{const user=await identity(r),project=text(new URL(r.url).searchParams.get('project'),100,true),access=await accessProject(project,user);return Response.json(await result(project,String(access.role)),{headers});}catch(error){return fail(error);}}
export async function PATCH(r:Request){try{const user=await identity(r),data=await body(r),project=text(data.project,100,true);await accessProject(project,user,'owner');const values=validatePolicy(data.policy),revision=data.policy.revision;if(!Number.isSafeInteger(revision)||revision<0)throw new HttpError(400,'Reload project settings before saving.');const before=await getProjectPolicy(project);if(before.revision!==revision)throw new HttpError(409,'Project settings changed. Reload them before saving again.');
 const now=Date.now(),changeId=crypto.randomUUID(),changedFields=policyFields.filter(key=>JSON.stringify(before[key])!==JSON.stringify(values[key]));
 const statements=[db().prepare('INSERT INTO project_policies (project,policy,revision,change_id,updated) SELECT ?,?,?,?,? WHERE ?=0 OR EXISTS (SELECT 1 FROM project_policies WHERE project=?) ON CONFLICT(project) DO UPDATE SET policy=excluded.policy,revision=excluded.revision,change_id=excluded.change_id,updated=excluded.updated WHERE project_policies.revision=? RETURNING revision').bind(project,JSON.stringify(values),revision+1,changeId,now,revision,project,revision)];
 if(before.auditEnabled||values.auditEnabled)statements.push(db().prepare("INSERT INTO project_policy_events (id,project,actor,action,details,created) SELECT ?,?,?,'policy.updated',?,? WHERE EXISTS (SELECT 1 FROM project_policies WHERE project=? AND change_id=?)").bind(crypto.randomUUID(),project,user,JSON.stringify({changedFields}),now,project,changeId));
 const saved=await db().batch(statements);if(!saved[0].results.length)throw new HttpError(409,'Project settings changed. Reload them before saving again.');return Response.json(await result(project,'owner'),{headers});}catch(error){return fail(error);}}
