'use client';
import {useEffect,useRef,useState} from 'react';
import {AudioLines,Image,ShieldCheck,Volume2,Download,ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {speechModels,transcriptionModels} from './lib/groq-models';
import './ai-tools.css';
type Task='speech'|'transcription'|'vision'|'safety';
type Props={open:boolean;onOpenChange:(value:boolean)=>void;projectId:string|null;onDraft:(text:string)=>void};
const tasks=[{id:'speech',name:'Text to speech',icon:Volume2,description:'Turn a short message into English or Saudi Arabic audio.'},{id:'transcription',name:'Speech to text',icon:AudioLines,description:'Transcribe an audio file in its original language.'},{id:'vision',name:'Image analysis',icon:Image,description:'Ask a question about a photo, screenshot, or document image.'},{id:'safety',name:'Text safety',icon:ShieldCheck,description:'Review text for potentially harmful content.'}] as const;
export default function AITools(p:Props){
 const [task,setTask]=useState<Task>('speech'),[model,setModel]=useState<string>(speechModels[0].id),[voice,setVoice]=useState('troy'),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(''),[audio,setAudio]=useState(''),[safety,setSafety]=useState<{flagged:boolean;category:string;explanation:string}|null>(null),[connection,setConnection]=useState<boolean|null>(null);
 const lock=useRef(false),upload=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!p.open)return;const c=new AbortController();setConnection(null);fetch('/api/ai-models',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Sign in to use AI tools.');return r.json() as Promise<{groq:boolean}>}).then(d=>setConnection(d.groq===true)).catch(e=>{if(!c.signal.aborted){setConnection(false);setError(e.message)}});return()=>c.abort()},[p.open]);
 useEffect(()=>()=>{if(audio)URL.revokeObjectURL(audio)},[audio]);
 function clear(){setResult('');setAudio('');setSafety(null);setError('')}
 function switchTask(next:Task){setTask(next);setText('');setFile(null);if(upload.current)upload.current.value='';clear();setModel(next==='transcription'?transcriptionModels[0].id:speechModels[0].id);setVoice('troy')}
 async function run(){if(lock.current)return;lock.current=true;setBusy(true);clear();try{
  const data=new FormData();data.set('task',task);data.set('model',model);data.set('voice',voice);data.set('text',text);if(p.projectId)data.set('project',p.projectId);if(file)data.set('file',file);
  const r=await fetch('/api/ai-tools',{method:'POST',body:data});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error||'The request failed. Please try again.')}
  if(task==='speech')setAudio(URL.createObjectURL(await r.blob()));else{const d=await r.json() as {text:string;flagged:boolean;category:string;explanation:string};if(task==='safety')setSafety(d);else setResult(d.text)}
 }catch(e){setError((e as Error).message)}finally{setBusy(false);lock.current=false}}
 const selectedSpeech=speechModels.find(m=>m.id===model)||speechModels[0],max=task==='speech'?200:task==='safety'?10000:4000;
 const valid=task==='transcription'?!!file:task==='vision'?!!file&&!!text.trim():!!text.trim();
 return <Dialog open={p.open} onOpenChange={value=>{if(!busy)p.onOpenChange(value)}}><DialogContent className="recoord-dialog ai-tools"><DialogTitle>AI tools</DialogTitle><DialogDescription>Work with words, voices, and images through Groq.</DialogDescription><nav className="ai-tool-tabs" aria-label="AI tools">{tasks.map(t=><button key={t.id} disabled={busy} aria-pressed={task===t.id} onClick={()=>switchTask(t.id)}><t.icon size={18}/>{t.name}</button>)}</nav><div className="ai-tools-content"><h3>{tasks.find(t=>t.id===task)?.name}</h3><p>{tasks.find(t=>t.id===task)?.description}</p><p className="ai-tool-privacy">Only what you submit here is sent to Groq. Results stay in this panel until you download them or use them in a chat draft. Recoord records request counts, status, and timing, not the tool’s content.</p>{connection===false&&<p role="status">These tools need the site’s Groq connection. You can prepare inputs now.</p>}<form onSubmit={e=>{e.preventDefault();void run()}}><fieldset disabled={busy}>
 {task==='speech'&&<div className="ai-tool-fields"><label>Language and model<select value={model} onChange={e=>{setModel(e.target.value);setVoice(e.target.value===speechModels[0].id?'troy':'noura');clear()}}>{speechModels.map(m=><option key={m.id} value={m.id}>{m.name} · Preview</option>)}</select></label><label>Voice<select value={voice} onChange={e=>{setVoice(e.target.value);clear()}}>{selectedSpeech.voices.map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label></div>}
 {task==='transcription'&&<label>Model<select value={model} onChange={e=>{setModel(e.target.value);clear()}}>{transcriptionModels.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}
 {task==='vision'&&<p className="ai-tool-model">Qwen 3.8 27B · Preview</p>}{task==='safety'&&<><p className="ai-tool-model">Safety GPT OSS 20B · Preview</p><details><summary>What this check reviews</summary><p>Violence, sexual exploitation of minors, targeted hate or harassment, self-harm encouragement, fraud, and credential theft. Context matters: educational discussion and quoted material should not be flagged merely for mentioning a topic. This is a review aid; it does not block posts or make enforcement decisions.</p></details></>}
 {(task==='transcription'||task==='vision')&&<label>{task==='vision'?'Image (PNG, JPEG, WebP · up to 2 MB)':'Audio (up to 5 MB)'}<input key={task} ref={upload} type="file" accept={task==='vision'?'image/png,image/jpeg,image/webp':'.flac,.mp3,.mp4,.mpeg,.mpga,.m4a,.ogg,.wav,.webm'} onChange={e=>{clear();const f=e.target.files?.[0]||null;if(f&&f.size>(task==='vision'?2:5)*1024*1024){setError('Choose a smaller file.');setFile(null);e.target.value=''}else setFile(f)}}/></label>}
 {task!=='transcription'&&<label>{task==='vision'?'Question about the image':task==='safety'?'Text to review':'Text to speak'}<textarea rows={5} maxLength={max} value={text} onChange={e=>{setText(e.target.value);clear()}} required placeholder={task==='vision'?'What does this image show?':task==='speech'?'Write a short message…':'Paste the text you want to review…'}/><small>{text.length.toLocaleString()} / {max.toLocaleString()} characters</small></label>}
 <button className="primary" disabled={busy||connection!==true||!valid}>{busy?'Working…':task==='speech'?'Generate speech':task==='transcription'?'Transcribe audio':task==='vision'?'Analyze image':'Check text'}</button></fieldset></form>
 {error&&<p className="form-error" role="alert">{error}</p>}{busy&&<p role="status">Waiting for Groq… You can leave this panel open while it works.</p>}
 {audio&&<section className="ai-tool-result" aria-label="Generated speech"><h4>Your audio</h4><audio controls src={audio}/><a href={audio} download="recoord-speech.wav"><Download size={15}/>Download WAV</a></section>}
 {result&&<section className="ai-tool-result" aria-label="AI tool result"><h4>{task==='transcription'?'Transcript':'Image analysis'}</h4><div className="ai-tool-output">{result}</div><button className="small-button" disabled={result.length>20000} onClick={()=>{p.onDraft(result);p.onOpenChange(false)}}>Use in chat draft <ArrowUpRight size={15}/></button>{result.length>20000&&<p>This result is too long for a chat draft. Download it instead.</p>}<button className="small-button" onClick={()=>{const u=URL.createObjectURL(new Blob([result],{type:'text/plain'})),a=document.createElement('a');a.href=u;a.download='recoord-'+task+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}><Download size={15}/>Download text</button></section>}
 {safety&&<section className="ai-tool-result" aria-label="Safety assessment"><h4>{safety.flagged?'Review suggested':'No policy issue detected'}</h4><strong>{safety.category}</strong><p>{safety.explanation}</p><small>AI can miss context or make mistakes. Review this assessment before acting.</small></section>}
 <p className="ai-tool-footnote">Each submission counts toward your AI limits. Preview models may change or require acceptance of provider terms in Groq. <a href="https://console.groq.com/docs/models" target="_blank" rel="noreferrer">Model details</a></p></div></DialogContent></Dialog>
}
