// Shared-link entries save references only; they are not connected-account integrations.
export const apps=[
{id:'github',name:'GitHub',category:'Development',mode:'README import',description:'Import a public repository README into project documents.'},
{id:'calendar',name:'Calendar',category:'Planning',mode:'Calendar export',description:'Export deadlines to Apple Calendar, Google Calendar, or Outlook.'},
{id:'markdown',name:'Markdown & text',category:'Documents',mode:'File import',description:'Import a Markdown or plain-text document.',accept:'.md,.txt'},
{id:'csv',name:'Spreadsheet snapshot',category:'Documents',mode:'File import',description:'Save an exported CSV from Excel or Google Sheets as a document.',accept:'.csv'},
{id:'tasks',name:'Task spreadsheet',category:'Planning',mode:'CSV export',description:'Download project tasks with status, assignee, and deadlines.'},
{id:'brief',name:'Project brief',category:'Documents',mode:'Markdown export',description:'Download a project’s goal and task summary.'},
{id:'documents',name:'Document bundle',category:'Documents',mode:'JSON export',description:'Download the project’s shared documents in one file.'},
{id:'figma',name:'Figma',category:'Design',mode:'Shared link',description:'Keep a design file or prototype beside your project.',hosts:['figma.com']},
{id:'canva',name:'Canva',category:'Design',mode:'Shared link',description:'Save a link to a design or presentation.',hosts:['canva.com']},
{id:'notion',name:'Notion',category:'Documents',mode:'Shared link',description:'Save a team page or knowledge-base link.',hosts:['notion.so','notion.site']},
{id:'drive',name:'Google Drive & Docs',category:'Documents',mode:'Shared link',description:'Keep a document, sheet, slide deck, or folder in reach.',hosts:['drive.google.com','docs.google.com']},
{id:'dropbox',name:'Dropbox',category:'Documents',mode:'Shared link',description:'Save a shared file or folder link.',hosts:['dropbox.com']},
{id:'slack',name:'Slack',category:'Communication',mode:'Shared link',description:'Reference a channel or message from your project.',hosts:['slack.com']},
{id:'teams',name:'Microsoft Teams',category:'Communication',mode:'Shared link',description:'Keep a team channel or meeting link together.',hosts:['teams.microsoft.com','teams.live.com']},
{id:'linear',name:'Linear',category:'Planning',mode:'Shared link',description:'Reference an issue or project in Linear.',hosts:['linear.app']},
{id:'trello',name:'Trello',category:'Planning',mode:'Shared link',description:'Keep a board or card linked to your project.',hosts:['trello.com']},
{id:'asana',name:'Asana',category:'Planning',mode:'Shared link',description:'Reference tasks and projects in Asana.',hosts:['asana.com']},
{id:'youtube',name:'YouTube',category:'Communication',mode:'Shared link',description:'Save a tutorial, recording, or demo video.',hosts:['youtube.com','youtu.be']},
{"id": "box", "name": "Box", "category": "Documents", "mode": "Shared link", "description": "Keep a shared file or folder with your project.", "hosts": ["box.com"]},
{"id": "onedrive", "name": "OneDrive", "category": "Documents", "mode": "Shared link", "description": "Reference a shared Microsoft file or folder.", "hosts": ["onedrive.live.com", "1drv.ms"]},
{"id": "sharepoint", "name": "SharePoint", "category": "Documents", "mode": "Shared link", "description": "Keep a team site or document library in reach.", "hosts": ["sharepoint.com"]},
{"id": "confluence", "name": "Confluence", "category": "Documents", "mode": "Shared link", "description": "Reference a team wiki page or specification.", "hosts": ["atlassian.net"]},
{"id": "coda", "name": "Coda", "category": "Documents", "mode": "Shared link", "description": "Save a working document or team hub.", "hosts": ["coda.io"]},
{"id": "quip", "name": "Quip", "category": "Documents", "mode": "Shared link", "description": "Reference a collaborative document.", "hosts": ["quip.com"]},
{"id": "evernote", "name": "Evernote", "category": "Documents", "mode": "Shared link", "description": "Save a shared research note.", "hosts": ["evernote.com"]},
{"id": "monday", "name": "monday.com", "category": "Planning", "mode": "Shared link", "description": "Reference a board, item, or project plan.", "hosts": ["monday.com"]},
{"id": "clickup", "name": "ClickUp", "category": "Planning", "mode": "Shared link", "description": "Save a task, document, or project link.", "hosts": ["clickup.com"]},
{"id": "airtable", "name": "Airtable", "category": "Planning", "mode": "Shared link", "description": "Keep a shared base or view with your project.", "hosts": ["airtable.com"]},
{"id": "basecamp", "name": "Basecamp", "category": "Planning", "mode": "Shared link", "description": "Reference a project or team discussion.", "hosts": ["basecamp.com"]},
{"id": "todoist", "name": "Todoist", "category": "Planning", "mode": "Shared link", "description": "Keep a task or project link in reach.", "hosts": ["todoist.com"]},
{"id": "jira", "name": "Jira", "category": "Planning", "mode": "Shared link", "description": "Reference an issue, sprint, or project board.", "hosts": ["atlassian.net"]},
{"id": "miro", "name": "Miro", "category": "Design", "mode": "Shared link", "description": "Save a workshop board or visual plan.", "hosts": ["miro.com"]},
{"id": "mural", "name": "Mural", "category": "Design", "mode": "Shared link", "description": "Keep a collaborative whiteboard in your project.", "hosts": ["mural.co"]},
{"id": "whimsical", "name": "Whimsical", "category": "Design", "mode": "Shared link", "description": "Reference a diagram, wireframe, or board.", "hosts": ["whimsical.com"]},
{"id": "framer", "name": "Framer", "category": "Design", "mode": "Shared link", "description": "Save a website design or preview link.", "hosts": ["framer.com", "framer.app", "framer.website"]},
{"id": "webflow", "name": "Webflow", "category": "Design", "mode": "Shared link", "description": "Reference a site preview or designer link.", "hosts": ["webflow.com", "webflow.io"]},
{"id": "behance", "name": "Behance", "category": "Design", "mode": "Shared link", "description": "Save a portfolio project for inspiration.", "hosts": ["behance.net"]},
{"id": "dribbble", "name": "Dribbble", "category": "Design", "mode": "Shared link", "description": "Collect design references beside your work.", "hosts": ["dribbble.com"]},
{"id": "loom", "name": "Loom", "category": "Media", "mode": "Shared link", "description": "Keep a walkthrough or feedback recording.", "hosts": ["loom.com"]},
{"id": "vimeo", "name": "Vimeo", "category": "Media", "mode": "Shared link", "description": "Save a video demo or review link.", "hosts": ["vimeo.com"]},
{"id": "figjam", "name": "FigJam", "category": "Design", "mode": "Shared link", "description": "Reference a FigJam planning board.", "hosts": ["figma.com"]},
{"id": "zoom", "name": "Zoom", "category": "Communication", "mode": "Shared link", "description": "Save a meeting link for your team.", "hosts": ["zoom.us"]},
{"id": "meet", "name": "Google Meet", "category": "Communication", "mode": "Shared link", "description": "Keep a meeting room link in your project.", "hosts": ["meet.google.com"]},
{"id": "discord", "name": "Discord", "category": "Communication", "mode": "Shared link", "description": "Reference a channel, message, or community invite.", "hosts": ["discord.com", "discord.gg"]},
{"id": "calendly", "name": "Calendly", "category": "Communication", "mode": "Shared link", "description": "Share a booking link with collaborators.", "hosts": ["calendly.com"]},
{"id": "gitlab", "name": "GitLab", "category": "Development", "mode": "Shared link", "description": "Reference a repository, merge request, or issue.", "hosts": ["gitlab.com"]},
{"id": "bitbucket", "name": "Bitbucket", "category": "Development", "mode": "Shared link", "description": "Save a repository or pull request link.", "hosts": ["bitbucket.org"]},
{"id": "codesandbox", "name": "CodeSandbox", "category": "Development", "mode": "Shared link", "description": "Keep a runnable prototype link with your project.", "hosts": ["codesandbox.io"]},
{"id": "codepen", "name": "CodePen", "category": "Development", "mode": "Shared link", "description": "Reference an interactive front-end example.", "hosts": ["codepen.io"]},
{"id": "replit", "name": "Replit", "category": "Development", "mode": "Shared link", "description": "Save a coding project or deployed demo link.", "hosts": ["replit.com", "replit.app"]},
{"id": "vercel", "name": "Vercel", "category": "Development", "mode": "Shared link", "description": "Reference a deployment or project dashboard.", "hosts": ["vercel.com", "vercel.app"]},
{"id": "netlify", "name": "Netlify", "category": "Development", "mode": "Shared link", "description": "Keep a deployment or site preview in reach.", "hosts": ["netlify.com", "netlify.app"]},
{"id": "sentry", "name": "Sentry", "category": "Development", "mode": "Shared link", "description": "Reference an error report for investigation.", "hosts": ["sentry.io"]},
{"id": "huggingface", "name": "Hugging Face", "category": "AI & research", "mode": "Shared link", "description": "Save a model, dataset, or Space for your team.", "hosts": ["huggingface.co"]},
{"id": "kaggle", "name": "Kaggle", "category": "AI & research", "mode": "Shared link", "description": "Reference a dataset, notebook, or experiment.", "hosts": ["kaggle.com"]},
{"id": "arxiv", "name": "arXiv", "category": "AI & research", "mode": "Shared link", "description": "Collect a research paper alongside your project.", "hosts": ["arxiv.org"]},
{"id": "colab", "name": "Google Colab", "category": "AI & research", "mode": "Shared link", "description": "Keep a shared research notebook in reach.", "hosts": ["colab.research.google.com"]},
{"id": "typeform", "name": "Typeform", "category": "Forms", "mode": "Shared link", "description": "Save a survey or feedback form.", "hosts": ["typeform.com"]},
{"id": "googleforms", "name": "Google Forms", "category": "Forms", "mode": "Shared link", "description": "Share a feedback or registration form.", "hosts": ["forms.gle", "docs.google.com"]},
{"id": "jotform", "name": "Jotform", "category": "Forms", "mode": "Shared link", "description": "Keep a form or survey with your project.", "hosts": ["jotform.com"]},
{"id": "salesforce", "name": "Salesforce", "category": "Customer work", "mode": "Shared link", "description": "Reference an account, opportunity, or customer record.", "hosts": ["salesforce.com", "force.com"]},
{"id": "hubspot", "name": "HubSpot", "category": "Customer work", "mode": "Shared link", "description": "Save a CRM record or campaign workspace link.", "hosts": ["hubspot.com"]},
{"id": "zendesk", "name": "Zendesk", "category": "Customer work", "mode": "Shared link", "description": "Reference a support ticket or help-center article.", "hosts": ["zendesk.com"]},
{"id": "intercom", "name": "Intercom", "category": "Customer work", "mode": "Shared link", "description": "Keep a customer conversation or help article in reach.", "hosts": ["intercom.com", "intercom.io"]},
{"id": "freshdesk", "name": "Freshdesk", "category": "Customer work", "mode": "Shared link", "description": "Reference a ticket or support knowledge base.", "hosts": ["freshdesk.com"]},
{"id": "helpscout", "name": "Help Scout", "category": "Customer work", "mode": "Shared link", "description": "Keep a support conversation or article linked to your work.", "hosts": ["helpscout.com", "helpscout.net"]},
{"id": "pipedrive", "name": "Pipedrive", "category": "Customer work", "mode": "Shared link", "description": "Save a deal or customer workspace link.", "hosts": ["pipedrive.com"]},
{"id": "zoho", "name": "Zoho", "category": "Customer work", "mode": "Shared link", "description": "Reference a CRM record or team workspace.", "hosts": ["zoho.com"]},
{"id": "mailchimp", "name": "Mailchimp", "category": "Marketing", "mode": "Shared link", "description": "Keep a campaign or audience workspace link.", "hosts": ["mailchimp.com"]},
{"id": "buffer", "name": "Buffer", "category": "Marketing", "mode": "Shared link", "description": "Reference a publishing queue or campaign workspace.", "hosts": ["buffer.com"]},
{"id": "hootsuite", "name": "Hootsuite", "category": "Marketing", "mode": "Shared link", "description": "Save a social publishing or analytics workspace link.", "hosts": ["hootsuite.com"]},
{"id": "brevo", "name": "Brevo", "category": "Marketing", "mode": "Shared link", "description": "Reference a campaign or contact workspace.", "hosts": ["brevo.com"]},
{"id": "linkedin", "name": "LinkedIn", "category": "Social & publishing", "mode": "Shared link", "description": "Save a professional profile, company page, or post.", "hosts": ["linkedin.com"]},
{"id": "instagram", "name": "Instagram", "category": "Social & publishing", "mode": "Shared link", "description": "Collect a profile, post, or reel as a project reference.", "hosts": ["instagram.com"]},
{"id": "tiktok", "name": "TikTok", "category": "Social & publishing", "mode": "Shared link", "description": "Keep a video or creator profile with your project.", "hosts": ["tiktok.com"]},
{"id": "pinterest", "name": "Pinterest", "category": "Social & publishing", "mode": "Shared link", "description": "Save an inspiration board or pin.", "hosts": ["pinterest.com", "pin.it"]},
{"id": "reddit", "name": "Reddit", "category": "Social & publishing", "mode": "Shared link", "description": "Reference a community discussion or post.", "hosts": ["reddit.com"]},
{"id": "medium", "name": "Medium", "category": "Social & publishing", "mode": "Shared link", "description": "Collect an article or publication link.", "hosts": ["medium.com"]},
{"id": "substack", "name": "Substack", "category": "Social & publishing", "mode": "Shared link", "description": "Save a newsletter article or publication.", "hosts": ["substack.com"]},
{"id": "wordpress", "name": "WordPress.com", "category": "Social & publishing", "mode": "Shared link", "description": "Keep a published article or site link.", "hosts": ["wordpress.com"]},
{"id": "obsidian", "name": "Obsidian Publish", "category": "Documents", "mode": "Shared link", "description": "Reference a published note or knowledge site.", "hosts": ["publish.obsidian.md"]},
{"id": "overleaf", "name": "Overleaf", "category": "Documents", "mode": "Shared link", "description": "Keep a research paper or shared writing project in reach.", "hosts": ["overleaf.com"]},
{"id": "readthedocs", "name": "Read the Docs", "category": "Documents", "mode": "Shared link", "description": "Save a documentation page for your team.", "hosts": ["readthedocs.io", "readthedocs.org"]},
{"id": "gitbook", "name": "GitBook", "category": "Documents", "mode": "Shared link", "description": "Reference product documentation or a team guide.", "hosts": ["gitbook.io", "gitbook.com"]},
{"id": "hackmd", "name": "HackMD", "category": "Documents", "mode": "Shared link", "description": "Keep a collaborative Markdown note with your project.", "hosts": ["hackmd.io"]},
{"id": "lucid", "name": "Lucidchart", "category": "Design", "mode": "Shared link", "description": "Reference a process diagram or architecture drawing.", "hosts": ["lucid.app", "lucidchart.com"]},
{"id": "excalidraw", "name": "Excalidraw", "category": "Design", "mode": "Shared link", "description": "Save a shared sketch or whiteboard link.", "hosts": ["excalidraw.com"]},
{"id": "penpot", "name": "Penpot", "category": "Design", "mode": "Shared link", "description": "Keep a design or prototype link with your project.", "hosts": ["penpot.app"]},
{"id": "spline", "name": "Spline", "category": "Design", "mode": "Shared link", "description": "Reference an interactive 3D scene or design.", "hosts": ["spline.design"]},
{"id": "tldraw", "name": "tldraw", "category": "Design", "mode": "Shared link", "description": "Save a shared canvas or visual brainstorm.", "hosts": ["tldraw.com"]},
{"id": "postman", "name": "Postman", "category": "Development", "mode": "Shared link", "description": "Reference an API collection, documentation, or workspace.", "hosts": ["postman.com"]},
{"id": "swagger", "name": "SwaggerHub", "category": "Development", "mode": "Shared link", "description": "Keep an API specification link in your project.", "hosts": ["swaggerhub.com"]},
{"id": "stackblitz", "name": "StackBlitz", "category": "Development", "mode": "Shared link", "description": "Save a browser-based development project.", "hosts": ["stackblitz.com"]},
{"id": "observable", "name": "Observable", "category": "AI & research", "mode": "Shared link", "description": "Reference a data notebook or visualization.", "hosts": ["observablehq.com"]},
{"id": "wandb", "name": "Weights & Biases", "category": "AI & research", "mode": "Shared link", "description": "Keep an experiment report or model evaluation link.", "hosts": ["wandb.ai"]},
{"id": "replicate", "name": "Replicate", "category": "AI & research", "mode": "Shared link", "description": "Save a model page or example for your team.", "hosts": ["replicate.com"]},
{"id": "dovetail", "name": "Dovetail", "category": "AI & research", "mode": "Shared link", "description": "Reference a research project or insight.", "hosts": ["dovetail.com"]},
{"id": "tally", "name": "Tally", "category": "Forms", "mode": "Shared link", "description": "Keep a survey or feedback form with your project.", "hosts": ["tally.so"]},
{"id": "surveymonkey", "name": "SurveyMonkey", "category": "Forms", "mode": "Shared link", "description": "Save a survey or results workspace link.", "hosts": ["surveymonkey.com"]},
{"id": "fillout", "name": "Fillout", "category": "Forms", "mode": "Shared link", "description": "Reference a form for feedback or registration.", "hosts": ["fillout.com"]},
{"id": "custom", "name": "Other app or website", "category": "Other", "mode": "Shared link", "description": "Save an HTTPS resource from another app or website.", "hosts": []},
] as const;
