"use client";
import {useEffect,useRef,useState} from "react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {Plus,MessageSquare,Menu,X,Send,FileText,Folder,Settings2,Download,Trash2,Check,Copy,Paperclip,PenLine,Compass,ListChecks,ArrowLeft,Save,Leaf,Home,Search,Command,ArrowUpRight,Blocks,Code2,Sparkles,ChevronRight,UserRound} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import Team,{Invitations} from './team';
import Integrations from './integrations';
import IntegrationShortcuts from './integration-shortcuts';
import ProjectGrid from './project-grid';
import HomeStart from './home-start';
import {usePreferences,shouldSend} from './preferences';
import WorkspaceSettings,{type SettingsSection} from './workspace-settings';
type Project={role:'owner'|'editor'|'viewer';id:string;title:string;goal:string;context:string;updated?:number;lastActivity?:number;taskCount?:number;completedCount?:number;documentCount?:number;memberCount?:number};
type DocumentItem={id:string;project:string;title:string;content:string;version:number};
type Conversation={id:string;title:string;project:string|null};
type Message={id:string;role:string;content:string};
type Snapshot={projects:Project[];conversations:Conversation[];documents:DocumentItem[]};
const empty:Snapshot={projects:[],conversations:[],documents:[]};
const journeys=[{name:"Plan a project",icon:ListChecks,goal:"Create an achievable plan with milestones and next steps.",prompt:"Help me plan this project. Start with the outcome, milestones, and first three actions."},{name:"Draft a document",icon:PenLine,goal:"Produce a clear, useful document for my audience.",prompt:"Help me draft a document. Ask about the audience and purpose, then create a first draft."},{name:"Compare options",icon:Compass,goal:"Compare the options, evidence, tradeoffs, and open questions.",prompt:"Help me make a decision. Lay out the options, tradeoffs, assumptions, and what I still need to learn."}];
async function api<T>(url:string,method="GET",data?:unknown):Promise<T>{const r=await fetch(url,{method,headers:data?{"Content-Type":"application/json"}:undefined,body:data?JSON.stringify(data):undefined});const value=await r.json() as T&{error?:string};if(!r.ok)throw new Error(value.error||"Something went wrong. Please try again.");return value;}
function download(name:string,content:string,type="text/markdown"){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function RichText({text}:{text:string}){return <div className="prose"><Markdown remarkPlugins={[remarkGfm]} skipHtml components={{a:({children,href})=><a href={href} target="_blank" rel="noreferrer">{children}</a>,table:({children})=><div className="table-scroll"><table>{children}</table></div>}}>{text}</Markdown></div>}
export default function Chat({user,ready,provider,model,signIn,signOut,preview=false}:{user:{id:string;name:string;email:string}|null;ready:boolean;provider:string;model:string;signIn:string;signOut:string;preview?:boolean}){
 const [data,setData]=useState<Snapshot>(empty),[projectId,setProjectId]=useState<string|null>(null),[conversationId,setConversationId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[sidebar,setSidebar]=useState(false),[tab,setTab]=useState("chat"),[settings,setSettings]=useState(false),[projectForm,setProjectForm]=useState(false),[editingProject,setEditingProject]=useState(false),[formTitle,setFormTitle]=useState(""),[formGoal,setFormGoal]=useState(""),[formContext,setFormContext]=useState(""),[formBusy,setFormBusy]=useState(false),[editor,setEditor]=useState<DocumentItem|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[draftStatus,setDraftStatus]=useState(""),[copied,setCopied]=useState(""),[sample,setSample]=useState(false),[deleteText,setDeleteText]=useState("");
 const {preferences,update:savePreferences,status:preferenceStatus}=usePreferences(user?.id||'guest');
 const [chatOnly,setChatOnly]=useState(false);
 useEffect(()=>{if(chatOnly)input.current?.focus()},[chatOnly]);
 const [settingsSection,setSettingsSection]=useState<SettingsSection>('account');
 function openSettings(section:SettingsSection='account'){setSidebar(false);setSettingsSection(section);setSettings(true)}
 const [integrationTool,setIntegrationTool]=useState<'all'|'github'|'calendar'>('all');
 function openIntegrations(tool:'all'|'github'|'calendar'='all'){setIntegrationTool(tool);setSidebar(false);setIntegrationsOpen(true)}
 const [integrationsOpen,setIntegrationsOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[workspaceQuery,setWorkspaceQuery]=useState('');
 const sidebarRef=useRef<HTMLElement>(null),menuRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSidebar(false);setSearchOpen(v=>!v);}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[]);
 useEffect(()=>{const media=window.matchMedia('(max-width:850px)');const resize=()=>{if(!media.matches)setSidebar(false)};media.addEventListener('change',resize);return()=>media.removeEventListener('change',resize)},[]);
 useEffect(()=>{if(!sidebar||!window.matchMedia('(max-width:850px)').matches)return;const previous=document.activeElement as HTMLElement|null;const elements=()=>Array.from(sidebarRef.current?.querySelectorAll<HTMLElement>('a[href],button:not(:disabled),input')||[]).filter(e=>e.getClientRects().length);elements()[0]?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSidebar(false);e.preventDefault()}if(e.key==='Tab'){const list=elements(),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);if(menuRef.current?.isConnected)menuRef.current.focus();else if(previous?.isConnected)previous.focus()}},[sidebar]);
 const [teamOpen,setTeamOpen]=useState(false),[teamDocument,setTeamDocument]=useState<string|undefined>();
 const project=data.projects.find(p=>p.id===projectId),scope=conversationId||("new:"+(projectId||"inbox"));
 const input=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null),contextFile=useRef<HTMLInputElement>(null),draftTimer=useRef<ReturnType<typeof setTimeout>|null>(null),draftChain=useRef(Promise.resolve()),draftText=useRef(""),loadVersion=useRef(0),requestId=useRef<string|null>(null),sendingRef=useRef(false);
 const storageKey=(s:string)=>"recoord:draft:"+(user?.id||"guest")+":"+s;
 function localDraft(s:string,value:string){try{sessionStorage.setItem(storageKey(s),value)}catch{}}
 function queueDraft(s:string,value:string,p:string|null){if(!user)return;draftChain.current=draftChain.current.catch(()=>{}).then(async()=>{await api('/api/drafts','PUT',{scope:s,content:value,project:p})});draftChain.current.then(()=>setDraftStatus("Draft saved")).catch(()=>setDraftStatus("Draft kept on this device; cloud save failed"));}
 function updateDraft(value:string){draftText.current=value;setDraft(value);localDraft(scope,value);requestId.current=null;if(draftTimer.current)clearTimeout(draftTimer.current);setDraftStatus(user?"Saving draft…":"Draft kept for sign-in");draftTimer.current=setTimeout(()=>queueDraft(scope,value,projectId),650)}
 async function flushDraft(){if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;queueDraft(scope,draftText.current,projectId)}await draftChain.current.catch(()=>{});}
 async function loadDraft(s:string){let value:string|null=null;try{value=sessionStorage.getItem(storageKey(s))}catch{}if(value===null&&user){try{value=(await api<{content:string}>('/api/drafts?scope='+encodeURIComponent(s))).content}catch{}}setDraft(value||"");draftText.current=value||"";setDraftStatus("");requestId.current=null;}
 async function refresh(p:string|null=projectId){if(!user)return;const value=await api<Snapshot>('/api/workspace'+(p?'?project='+encodeURIComponent(p):''));setData(value);return value;}
 useEffect(()=>{let active=true;(async()=>{try{if(user){let pending="";try{pending=sessionStorage.getItem("recoord:signin-draft")||"";sessionStorage.removeItem("recoord:signin-draft")}catch{}const initialProject=new URLSearchParams(window.location.search).get('project');const initial=await api<Snapshot>('/api/workspace'+(initialProject?'?project='+encodeURIComponent(initialProject):''));if(!active)return;setData(initial);if(initialProject){setProjectId(initialProject);const view=new URLSearchParams(window.location.search).get('view');setTeamOpen(view!=='chat'&&view!=='documents');setTab(view==='documents'?'document':'chat');}if(pending){setDraft(pending);draftText.current=pending;localDraft('new:inbox',pending);queueDraft('new:inbox',pending,null)}else await loadDraft('new:'+(initialProject||'inbox'))}else await loadDraft('new:inbox')}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false;if(draftTimer.current)clearTimeout(draftTimer.current)}},[]);
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('invite'))setNotice('Sign in with your invited email. Your invitation appears in the sidebar; choose Join project to accept.')},[]);
 useEffect(()=>{if(projectId){const q=new URLSearchParams({project:projectId,view:teamOpen?'board':tab==='document'?'documents':'chat'});window.history.replaceState(null,'','?'+q)}},[projectId,teamOpen,tab]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'stage_chat_message',description:'Place a draft in the visible composer for review; does not send it.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:20000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(value:{text?:unknown})=>{if(typeof value.text!=='string'||value.text.length>20000)throw new Error('Text must be under 20,000 characters');updateDraft(value.text);return {staged:true}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[scope]);
 function login(){try{sessionStorage.setItem("recoord:signin-draft",draftText.current)}catch{}window.location.assign(signIn)}
 function discard(){return !dirty||confirm('Discard your unsaved document edits?')}
 async function switchProject(id:string|null){if(busy||loading||!discard())return;await flushDraft();const version=++loadVersion.current;setLoading(true);setError('');try{const next=user?await api<Snapshot>('/api/workspace'+(id?'?project='+id:'')):empty;if(version!==loadVersion.current)return;setData(next);setProjectId(id);setChatOnly(false);setTeamOpen(!!id);window.history.replaceState(null,'',id?'?project='+encodeURIComponent(id):'/');setTeamDocument(undefined);setConversationId(null);setMessages([]);setEditor(null);setDirty(false);setSample(false);setTab('chat');setSidebar(false);await loadDraft('new:'+(id||'inbox'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function signOutAccount(){if(!user)return;if(!discard())return;await flushDraft();try{Object.keys(sessionStorage).filter(k=>k.startsWith('recoord:draft:'+user.id+':')).forEach(k=>sessionStorage.removeItem(k))}catch{}window.location.assign(signOut)}
 async function newChat(){if(busy||loading)return;setChatOnly(true);setTeamOpen(false);await flushDraft();setConversationId(null);setMessages([]);setSample(false);await loadDraft('new:'+(projectId||'inbox'));setTab('chat');input.current?.focus()}
 async function openConversation(id:string){if(busy||loading)return;setChatOnly(true);setTeamOpen(false);await flushDraft();setLoading(true);setError('');try{const value=await api<Message[]>('/api/messages?id='+id);setConversationId(id);setMessages(value);setSample(false);await loadDraft(id);setSidebar(false);setTab('chat')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 function openProjectForm(index?:number){setSidebar(false);if(!user){login();return}setEditingProject(false);setFormTitle('');setFormGoal(index===undefined?'':journeys[index].goal);setFormContext('');setProjectForm(true)}
 function editProject(){if(!project)return;setEditingProject(true);setFormTitle(project.title);setFormGoal(project.goal);setFormContext(project.context);setProjectForm(true)}
 async function saveProject(){setFormBusy(true);setError('');try{const id=editingProject?projectId!:crypto.randomUUID();await api('/api/workspace',editingProject?'PATCH':'POST',{kind:'project',id,title:formTitle,goal:formGoal,context:formContext});setProjectForm(false);if(editingProject)await refresh();else await switchProject(id)}catch(e){setError((e as Error).message)}finally{setFormBusy(false)}}
 function showSample(){if(!discard())return;setSample(true);setEditor(null);setDirty(false);setTab('chat');setMessages([{id:'example-user',role:'user',content:'Help me plan a small business website launch.'},{id:'example-assistant',role:'assistant',content:'# Website launch plan\n\n**Goal:** Publish a clear, useful website in two weeks.\n\n## Week 1 — Shape the essentials\n- Define your audience and the action visitors should take.\n- Draft the home, services, and contact pages.\n- Gather your logo, photos, and business details.\n\n## Week 2 — Build and check\n- Build the pages and connect your domain.\n- Test the mobile experience and contact form.\n- Ask three people to review it before launch.\n\n## Next three actions\n1. Write your one-sentence value proposition.\n2. List your three main services.\n3. Choose a launch date.\n\n**Open question:** Who will maintain the website after launch?'}])}
 async function createDocument(content=''){if(!user){login();return}if(project?.role==='viewer'){setNotice('Viewer access: shared documents are read-only.');return}if(!projectId){setNotice('Create or select a project before saving a document.');return}if(!discard())return;setEditor({id:crypto.randomUUID(),project:projectId,title:'Untitled document',content,version:0});setDirty(true);setTeamOpen(false);setTab('document');setNotice('Review your document, give it a title, then save.')}
 async function saveDocument(){if(!editor)return;setSaving(true);setError('');const snapshot={...editor};try{if(!snapshot.version){await api('/api/workspace','POST',{...snapshot,kind:'document'});setEditor({...snapshot,version:1})}else{const saved=await api<{version:number}>('/api/workspace','PATCH',{...snapshot,kind:'document'});setEditor({...snapshot,version:saved.version})}setDirty(false);setNotice('Document saved.');await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function deleteItem(kind:'project'|'document'|'conversation',id:string,title:string){if(busy||saving||!confirm(`Delete “${title}”? ${kind==='project'?'Its conversations, documents, and drafts will also be removed. ':''}This cannot be undone.`))return;await flushDraft();try{if(kind==='conversation')await api('/api/conversations?id='+id,'DELETE');else await api('/api/workspace','DELETE',{kind,id});if(kind==='project'){try{Object.keys(sessionStorage).filter(k=>k.startsWith('recoord:draft:'+user?.id+':')).forEach(k=>sessionStorage.removeItem(k))}catch{}setDirty(false);setProjectId(null);setConversationId(null);setEditor(null);setMessages([]);setData(await api('/api/workspace'));await loadDraft('new:inbox')}else{if(kind==='document'&&editor?.id===id){setEditor(null);setDirty(false)}if(kind==='conversation'&&conversationId===id){localDraft(id,'');setConversationId(null);setMessages([]);await loadDraft('new:'+(projectId||'inbox'))}await refresh()}setNotice('Deleted.')}catch(e){setError((e as Error).message)}}
 async function exportData(projectOnly=false){try{const value=await api('/api/export'+(projectOnly&&projectId?'?project='+projectId:''));download(projectOnly?'recoord-project.json':'recoord-workspace.json',JSON.stringify(value,null,2),'application/json')}catch(e){setError((e as Error).message)}}
 async function deleteAll(){if(deleteText!=='DELETE MY DATA')return;await flushDraft();try{await api('/api/data','DELETE',{confirm:deleteText});try{Object.keys(sessionStorage).filter(k=>k.startsWith('recoord:draft:'+user?.id+':')).forEach(k=>sessionStorage.removeItem(k))}catch{}setData(empty);setProjectId(null);setConversationId(null);setMessages([]);setEditor(null);setDirty(false);setDraft('');draftText.current='';setDeleteText('');setSettings(false);setNotice('Your saved Recoord content has been deleted. Your sign-in account is unchanged.')}catch(e){setError((e as Error).message)}}
 async function send(){if(busy||loading||sendingRef.current||!draft.trim())return;if(!user){login();return}if(!ready){setError('AI is not connected yet. Your draft is saved; projects and documents still work.');return}sendingRef.current=true;setBusy(true);await flushDraft();const id=conversationId||crypto.randomUUID(),content=draft.trim(),submission=requestId.current||crypto.randomUUID();requestId.current=submission;const previous=sample?[]:messages;setSample(false);setBusy(true);setError('');setMessages([...previous,{id:submission,role:'user',content},{id:submission+':reply',role:'assistant',content:''}]);let accepted=false,done=false;
 try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,project:projectId,requestId:submission,content,draftScope:scope})});if(!r.ok){const value=await r.json() as {error:string};throw new Error(value.error)}accepted=true;setConversationId(id);setDraft('');draftText.current='';localDraft(scope,'');setDraftStatus('');const reader=r.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const chunk=await reader.read();buffer+=chunk.done?decoder.decode():decoder.decode(chunk.value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';if(chunk.done&&buffer)lines.push(buffer);for(const line of lines){if(!line)continue;const value=JSON.parse(line);if(value.delta)setMessages(m=>m.map(x=>x.id===submission+':reply'?{...x,content:x.content+value.delta}:x));if(value.done)done=true;if(value.error)throw new Error(value.error)}if(chunk.done)break}if(!done)throw new Error('The connection was interrupted. Reopen the conversation to check the saved reply.');requestId.current=null;await refresh()}catch(e){setError((e as Error).message);if(!accepted)setMessages(previous);else{setMessages(m=>m.map(x=>x.id===submission+':reply'?{...x,content:x.content+'\n\n[Incomplete reply — check saved conversation.]'}:x));await refresh().catch(()=>{})}}finally{sendingRef.current=false;setBusy(false)}}
 return <div className="app"><aside ref={sidebarRef} aria-label="Workspace navigation" className={'sidebar '+(sidebar?'open':'')}><a className="brand" href="/" aria-label="Recoord home"><img className="brand-symbol" src="/recoord-mark.svg" alt="" width={36} height={36}/><span className="brand-wordmark">recoord</span></a><button className="new" onClick={()=>openProjectForm()} disabled={busy}><Plus size={17}/>Create project</button><button className="workspace-search" onClick={()=>{setSidebar(false);setSearchOpen(true)}}><Search size={16}/><span>Search workspace</span><kbd>⌘ K</kbd></button><p className="eyebrow">Workspace</p><button className={'nav-item '+(!projectId&&!chatOnly&&!messages.length?'selected':'')} onClick={()=>switchProject(null)}><Home size={17}/>Home</button><p className="eyebrow project-label">Projects <span>{data.projects.length}</span></p>{user&&<Invitations joined={id=>void switchProject(id)}/>}<div className="project-list">{data.projects.map(p=><button className={'nav-item '+(projectId===p.id?'selected':'')} key={p.id} onClick={()=>switchProject(p.id)} disabled={busy}><Folder size={17}/><span>{p.title}</span><small className="project-role">{p.role==='owner'?'':p.role}</small></button>)}{!data.projects.length&&<p className="empty-note">A place for your goals,<br/>conversations, and drafts.</p>}</div><p className="eyebrow">Your chats <span className="private-tag">Private</span></p><div className="history">{data.conversations.map(c=><div className={'history-item '+(conversationId===c.id?'selected':'')} key={c.id}><button disabled={busy||loading} onClick={()=>openConversation(c.id)}><MessageSquare size={14}/><span>{c.title}</span></button><button aria-label={'Delete '+c.title} onClick={()=>deleteItem('conversation',c.id,c.title)}><Trash2 size={13}/></button></div>)}</div><div className="sidebar-bottom"><div className="footer-tools"><button className="footer-tool" onClick={()=>{openIntegrations()}}><span className="footer-tool-icon"><Blocks size={17}/></span><span><strong>Integrations</strong><small>GitHub & calendar</small></span><ChevronRight size={14}/></button><button className="footer-tool" onClick={()=>openSettings('account')}><span className="footer-tool-icon"><Settings2 size={17}/></span><span><strong>Settings</strong><small>Preferences & account</small></span><ChevronRight size={14}/></button></div>{user?<button className="account-control" onClick={()=>openSettings('account')} aria-label="Open account settings"><span className="avatar">{preview?'P':(user.name.trim()[0]||'R').toUpperCase()}</span><span className="account-details"><strong>{preview?'Preview account':user.name}</strong><small>{preview?'Local testing only':'Personal account'}</small></span><ChevronRight size={14}/></button>:<button className="sign-in" onClick={login}>Sign in with ChatGPT</button>}</div></aside>{sidebar&&<button className="scrim" aria-label="Close menu" onClick={()=>setSidebar(false)}/>}
 <main inert={sidebar||undefined}><header><div className="header-title"><button ref={menuRef} className="icon mobile" aria-label="Open menu" aria-expanded={sidebar} onClick={()=>setSidebar(true)}><Menu size={20}/></button><span className="breadcrumb">Recoord <span>/</span></span><strong>{project?.title||data.conversations.find(c=>c.id===conversationId)?.title||(chatOnly?'Private chat':user?'Home':'Recoord')}</strong></div><div className="header-actions"><button className="connection-status connection-button" onClick={()=>openSettings('ai')} aria-label="View AI connection"><i className={ready?'online':''}/>{preview?'Local preview':ready?'AI connected':'AI not connected'}</button>{project&&<button className="icon" aria-label="Project settings" onClick={editProject}><Settings2 size={18}/></button>}<button className="small-button" disabled={busy||loading} onClick={newChat}><PenLine size={15}/>New chat</button></div></header>
 {project&&<div className="project-navigation"><nav aria-label="Project views" className="project-segments"><button aria-current={teamOpen?'page':undefined} onClick={()=>{setTeamDocument(undefined);setTeamOpen(true)}}><ListChecks size={16}/>Overview</button><button aria-current={!teamOpen&&tab==='chat'?'page':undefined} onClick={()=>{setTeamOpen(false);setTab('chat')}}><Sparkles size={16}/>AI chat</button><button aria-current={!teamOpen&&tab==='document'?'page':undefined} onClick={()=>{setTeamOpen(false);setTab('document')}}><FileText size={16}/>Documents <span>{data.documents.length}</span></button></nav><button className="icon" aria-label="Export project" onClick={()=>exportData(true)}><Download size={16}/></button></div>}

 {(error||notice)&&<div className={error?'error-banner':'notice-banner'} role={error?'alert':'status'}><span>{error||notice}</span><button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('')}}><X size={16}/></button></div>}

 {project&&teamOpen&&<Team key={project.id+':'+(teamDocument||'')} project={project.id} user={user!.id} title={project.title} goal={project.goal} initialDocument={teamDocument}/>}<div style={teamOpen?{display:'none'}:undefined} className={'work-area '+(projectId?'with-project ':'')+(projectId&&tab==='document'?'documents-view':'')}><section className={'chat-column '+(projectId&&tab==='document'?'view-hidden':'')}>
 {!messages.length&&user&&!projectId&&!chatOnly?<div className="workspace-home"><HomeStart sendMode={preferences.send} draft={draft} onDraft={updateDraft} onSend={()=>{setChatOnly(true);void send()}} onContinue={()=>setChatOnly(true)} onCreate={()=>openProjectForm()} onConnection={()=>openSettings('ai')} ready={ready} preview={preview} busy={busy||loading} draftStatus={draftStatus}/><ProjectGrid view={preferences.layout} onViewChange={layout=>savePreferences({...preferences,layout})} projects={data.projects} disabled={busy||loading} onOpen={id=>void switchProject(id)} onCreate={()=>openProjectForm()}/><IntegrationShortcuts onSelect={openIntegrations}/></div>:!messages.length?<div className="welcome"><span className="kicker">{chatOnly?'Private AI chat':'A LITTLE SPACE TO THINK'}</span><h1>{project?'Let’s move this forward.':chatOnly?'A little space to think.':<>Big ideas.<br/>Clear next steps.</>}</h1><p>{project?'Your AI chats are private. Saved project documents are shared with teammates.':chatOnly?'This conversation is private. Start with a question or choose a prompt below.':'Create a project. Make a plan, shape a draft, or work through a decision.'}</p><div className="journeys">{journeys.map((j,i)=><button key={j.name} onClick={()=>{if(project||chatOnly)updateDraft(j.prompt);else openProjectForm(i)}}><j.icon size={22}/><strong>{j.name}</strong><span>{i===0?'Find your next steps':i===1?'Get the first version down':'See the tradeoffs clearly'}</span></button>)}</div><button className="sample-link" onClick={showSample}>See an example</button></div>:<div className="messages" aria-label="Conversation">{sample&&<div className="sample-label">Sample conversation · written example, not a live AI response</div>}{messages.map(m=><article className={'message '+m.role} key={m.id}><div className="message-label">{m.role==='user'?'You':'Recoord'}</div><RichText text={m.content}/>{busy&&!m.content&&<span className="thinking">Working on it…</span>}{m.content&&<div className="message-actions"><button aria-label="Copy message" onClick={async()=>{try{await navigator.clipboard.writeText(m.content);setCopied(m.id)}catch{setError('Copy isn’t available. Select the text to copy it.')}}}>{copied===m.id?<Check size={14}/>:<Copy size={14}/>}Copy</button>{m.role==='assistant'&&<button onClick={()=>createDocument(m.content)}><FileText size={14}/>Save as document</button>}</div>}</article>)}<div ref={bottom}/></div>}
 <div className="compose-area" style={user&&!projectId&&!chatOnly&&!messages.length?{display:'none'}:undefined}>{!ready&&<div className="readiness">{preview?'Local preview · AI not connected.':'AI is not connected yet.'} {user?'Your projects and documents are ready to use.':'Sign in to save projects and documents.'}</div>}<form className="composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea ref={input} aria-label="Message Recoord" placeholder={project?'What would you like to work on?':'Start with an idea, a question, or an outcome…'} value={draft} maxLength={20000} onChange={e=>updateDraft(e.target.value)} onKeyDown={e=>{if(shouldSend(e,preferences.send)){e.preventDefault();void send()}}}/><div className="compose-footer"><div className="compose-tools"><input ref={file} hidden type="file" accept=".txt,.md,.csv,.json,.js,.ts,.py" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>16000){setError('Choose a text file under 16 KB.');return}const next=draft+'\n\nReference: '+f.name+'\n'+await f.text();if(next.length>20000){setError('Message and attachment must fit within 20,000 characters.');return}updateDraft(next)}}/><button type="button" className="icon" aria-label="Attach text file" onClick={()=>file.current?.click()}><Paperclip size={18}/></button><button className="model-label" type="button" onClick={()=>openSettings('ai')}>{ready?model:'No model connected'}</button></div><button className="send" aria-label="Send message" disabled={busy||loading||!draft.trim()}><Send size={18}/></button></div></form><div className="compose-note"><span>{draftStatus||(preferences.send==='enter'?'Enter to send · Shift + Enter for a new line':'⌘ / Ctrl + Enter to send')}</span><span>AI can make mistakes.</span></div></div>
 </section>{project&&<aside className={'document-panel '+(tab==='chat'?'view-hidden':'')}><div className="panel-heading"><h2><FileText size={18}/>Project documents</h2><button className="icon" aria-label="New document" onClick={()=>createDocument()}><Plus size={18}/></button></div><div className="document-list">{data.documents.map(d=><button className={editor?.id===d.id?'selected':''} key={d.id} onClick={()=>{if(discard()){setEditor({...d});setDirty(false)}}}><FileText size={15}/><span>{d.title}</span></button>)}</div>{editor?<div className="editor"><label className="sr-only" htmlFor="document-title">Document title</label><input id="document-title" value={editor.title} maxLength={100} disabled={saving||project?.role==='viewer'} onChange={e=>{setEditor({...editor,title:e.target.value});setDirty(true)}}/><button className="small-button" onClick={()=>{setTeamDocument(editor.id);setTeamOpen(true)}} disabled={!editor.version}>Discussion</button><div className="editor-status" role="status">{saving?'Saving…':dirty?'Unsaved changes':'Saved'} · Markdown supported</div><textarea aria-label="Document content" value={editor.content} maxLength={100000} disabled={saving||project?.role==='viewer'} onChange={e=>{setEditor({...editor,content:e.target.value});setDirty(true)}}/><div className="editor-actions"><button className="primary" disabled={saving||project?.role==='viewer'||!editor.title.trim()||!dirty} onClick={saveDocument}><Save size={15}/>Save</button><button className="small-button" onClick={()=>download(editor.title.replace(/[^a-z0-9 -]/gi,'').slice(0,60)+'.md',editor.content)}><Download size={15}/>Export</button>{editor.version>0&&project?.role!=='viewer'&&<button className="icon" aria-label="Delete document" onClick={()=>deleteItem('document',editor.id,editor.title)}><Trash2 size={16}/></button>}</div></div>:<div className="document-empty"><FileText size={30}/><h3>Your best work, saved.</h3><p>Save an answer as a document, or start your own. Edit it here and pick up where you left off.</p><button className="small-button" onClick={()=>createDocument()}>Create a document</button></div>}</aside>}</div></main>
 <Integrations initialTool={integrationTool} onCreateProject={()=>{setIntegrationsOpen(false);openProjectForm()}} open={integrationsOpen} onOpenChange={setIntegrationsOpen} projects={data.projects} projectId={projectId} onImported={id=>{setNotice('GitHub README imported into project documents.');void refresh(projectId);}}/>
 <Dialog open={searchOpen} onOpenChange={v=>{setSearchOpen(v);if(!v)setWorkspaceQuery('')}}><DialogContent onCloseAutoFocus={e=>{if(window.matchMedia('(max-width:850px)').matches){e.preventDefault();menuRef.current?.focus()}}} className="recoord-dialog search-dialog"><DialogTitle>Find your work</DialogTitle><DialogDescription>Search your projects and the chats in this workspace.</DialogDescription><label className="global-search-input"><Search size={19}/><input autoFocus aria-label="Search projects and chats" placeholder="Search projects and chats…" value={workspaceQuery} onChange={e=>setWorkspaceQuery(e.target.value)}/></label><div className="search-results"><h3>Projects</h3>{data.projects.filter(p=>p.title.toLowerCase().includes(workspaceQuery.toLowerCase())).map(p=><button disabled={busy||loading} key={p.id} onClick={()=>{setSearchOpen(false);void switchProject(p.id)}}><Folder size={17}/><span>{p.title}</span><ArrowUpRight size={15}/></button>)}<h3>Your chats</h3>{data.conversations.filter(c=>c.title.toLowerCase().includes(workspaceQuery.toLowerCase())).map(c=><button disabled={busy||loading} key={c.id} onClick={()=>{setSearchOpen(false);void openConversation(c.id)}}><MessageSquare size={17}/><span>{c.title}</span><ArrowUpRight size={15}/></button>)}{!data.projects.some(p=>p.title.toLowerCase().includes(workspaceQuery.toLowerCase()))&&!data.conversations.some(c=>c.title.toLowerCase().includes(workspaceQuery.toLowerCase()))&&<p className="search-empty">No matches. Try another name.</p>}</div></DialogContent></Dialog>
 <Dialog open={projectForm} onOpenChange={v=>{if(!formBusy)setProjectForm(v)}}><DialogContent onCloseAutoFocus={e=>{if(window.matchMedia('(max-width:850px)').matches){e.preventDefault();menuRef.current?.focus()}}} className="recoord-dialog"><DialogTitle>{editingProject?'Project settings':'Create a project'}</DialogTitle><DialogDescription>Keep a goal, useful context, and finished work together.</DialogDescription><form onSubmit={e=>{e.preventDefault();void saveProject()}}><label>Project name<input value={formTitle} maxLength={100} required onChange={e=>setFormTitle(e.target.value)} placeholder="e.g. Launch my business website"/></label><label>What do you want to achieve?<textarea value={formGoal} maxLength={4000} onChange={e=>setFormGoal(e.target.value)} placeholder="A specific outcome makes a useful starting point."/></label><label>Reference context<textarea value={formContext} maxLength={16000} onChange={e=>setFormContext(e.target.value)} placeholder="Background, requirements, or notes the assistant should use."/></label><p className="form-hint">This context is sent to the model with each message in this project. Edit or remove it anytime.</p><input ref={contextFile} type="file" hidden accept=".txt,.md,.csv,.json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const next=formContext+'\n\n'+f.name+'\n'+await f.text();if(f.size>16000||next.length>16000){setError('Project context must fit within 16,000 characters.');return}setFormContext(next)}}/><button type="button" className="small-button" onClick={()=>contextFile.current?.click()}><Paperclip size={15}/>Add text file</button>{error&&<p role="alert" className="form-error">{error}</p>}<div className="dialog-actions">{editingProject&&project?.role==='owner'&&<button type="button" className="danger" onClick={async()=>{await deleteItem('project',projectId!,formTitle);setProjectForm(false)}}>Delete project</button>}<button className="primary" disabled={formBusy||!formTitle.trim()||(editingProject&&project?.role==='viewer')}>{formBusy?'Saving…':editingProject?'Save changes':'Create project'}</button></div></form></DialogContent></Dialog>
 <WorkspaceSettings preferences={preferences} onPreferences={savePreferences} preferenceStatus={preferenceStatus} onIntegrations={()=>{setSettings(false);openIntegrations()}} open={settings} onOpenChange={setSettings} section={settingsSection} onSectionChange={setSettingsSection} user={user} preview={preview} ready={ready} provider={provider} model={model} onSignOut={signOutAccount} onSignIn={login} onExport={()=>exportData()} onDelete={deleteAll} deleteText={deleteText} onDeleteTextChange={setDeleteText} error={error} onMobileClose={()=>menuRef.current?.focus()}/>
 </div>
}
