"use client";
import {useEffect,useRef,useState} from "react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {Plus,MessageSquare,Menu,X,Send,FileText,Folder,Settings2,Download,Trash2,Check,Copy,Paperclip,PenLine,Compass,ListChecks,ArrowLeft,Save,Leaf} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import Team,{Invitations} from './team';
type Project={role:'owner'|'editor'|'viewer';id:string;title:string;goal:string;context:string};
type DocumentItem={id:string;project:string;title:string;content:string;version:number};
type Conversation={id:string;title:string;project:string|null};
type Message={id:string;role:string;content:string};
type Snapshot={projects:Project[];conversations:Conversation[];documents:DocumentItem[]};
const empty:Snapshot={projects:[],conversations:[],documents:[]};
const journeys=[{name:"Plan a project",icon:ListChecks,goal:"Create an achievable plan with milestones and next steps.",prompt:"Help me plan this project. Start with the outcome, milestones, and first three actions."},{name:"Draft a document",icon:PenLine,goal:"Produce a clear, useful document for my audience.",prompt:"Help me draft a document. Ask about the audience and purpose, then create a first draft."},{name:"Compare options",icon:Compass,goal:"Compare the options, evidence, tradeoffs, and open questions.",prompt:"Help me make a decision. Lay out the options, tradeoffs, assumptions, and what I still need to learn."}];
async function api<T>(url:string,method="GET",data?:unknown):Promise<T>{const r=await fetch(url,{method,headers:data?{"Content-Type":"application/json"}:undefined,body:data?JSON.stringify(data):undefined});const value=await r.json() as T&{error?:string};if(!r.ok)throw new Error(value.error||"Something went wrong. Please try again.");return value;}
function download(name:string,content:string,type="text/markdown"){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function RichText({text}:{text:string}){return <div className="prose"><Markdown remarkPlugins={[remarkGfm]} skipHtml components={{a:({children,href})=><a href={href} target="_blank" rel="noreferrer">{children}</a>,table:({children})=><div className="table-scroll"><table>{children}</table></div>}}>{text}</Markdown></div>}
export default function Chat({user,ready,provider,model,signIn,signOut}:{user:{id:string;name:string;email:string}|null;ready:boolean;provider:string;model:string;signIn:string;signOut:string}){
 const [data,setData]=useState<Snapshot>(empty),[projectId,setProjectId]=useState<string|null>(null),[conversationId,setConversationId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[sidebar,setSidebar]=useState(false),[tab,setTab]=useState("chat"),[settings,setSettings]=useState(false),[projectForm,setProjectForm]=useState(false),[editingProject,setEditingProject]=useState(false),[formTitle,setFormTitle]=useState(""),[formGoal,setFormGoal]=useState(""),[formContext,setFormContext]=useState(""),[formBusy,setFormBusy]=useState(false),[editor,setEditor]=useState<DocumentItem|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[draftStatus,setDraftStatus]=useState(""),[copied,setCopied]=useState(""),[sample,setSample]=useState(false),[deleteText,setDeleteText]=useState("");
 const [chatOnly,setChatOnly]=useState(false);
 const [teamOpen,setTeamOpen]=useState(false),[teamDocument,setTeamDocument]=useState<string|undefined>();
 const project=data.projects.find(p=>p.id===projectId),scope=conversationId||("new:"+(projectId||"inbox"));
 const input=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null),contextFile=useRef<HTMLInputElement>(null),draftTimer=useRef<ReturnType<typeof setTimeout>|null>(null),draftChain=useRef(Promise.resolve()),draftText=useRef(""),loadVersion=useRef(0),requestId=useRef<string|null>(null);
 const storageKey=(s:string)=>"recoord:draft:"+(user?.id||"guest")+":"+s;
 function localDraft(s:string,value:string){try{sessionStorage.setItem(storageKey(s),value)}catch{}}
 function queueDraft(s:string,value:string,p:string|null){if(!user)return;draftChain.current=draftChain.current.catch(()=>{}).then(async()=>{await api('/api/drafts','PUT',{scope:s,content:value,project:p})});draftChain.current.then(()=>setDraftStatus("Draft saved")).catch(()=>setDraftStatus("Draft kept on this device; cloud save failed"));}
 function updateDraft(value:string){draftText.current=value;setDraft(value);localDraft(scope,value);requestId.current=null;if(draftTimer.current)clearTimeout(draftTimer.current);setDraftStatus(user?"Saving draft…":"Draft kept for sign-in");draftTimer.current=setTimeout(()=>queueDraft(scope,value,projectId),650)}
 async function flushDraft(){if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;queueDraft(scope,draftText.current,projectId)}await draftChain.current.catch(()=>{});}
 async function loadDraft(s:string){let value:string|null=null;try{value=sessionStorage.getItem(storageKey(s))}catch{}if(value===null&&user){try{value=(await api<{content:string}>('/api/drafts?scope='+encodeURIComponent(s))).content}catch{}}setDraft(value||"");draftText.current=value||"";setDraftStatus("");requestId.current=null;}
 async function refresh(p:string|null=projectId){if(!user)return;const value=await api<Snapshot>('/api/workspace'+(p?'?project='+encodeURIComponent(p):''));setData(value);return value;}
 useEffect(()=>{let active=true;(async()=>{try{if(user){let pending="";try{pending=sessionStorage.getItem("recoord:signin-draft")||"";sessionStorage.removeItem("recoord:signin-draft")}catch{}const initialProject=new URLSearchParams(window.location.search).get('project');const initial=await api<Snapshot>('/api/workspace'+(initialProject?'?project='+encodeURIComponent(initialProject):''));if(!active)return;setData(initial);if(initialProject){setProjectId(initialProject);const view=new URLSearchParams(window.location.search).get('view');setTeamOpen(view!=='chat'&&view!=='documents');setTab(view==='documents'?'document':'chat');}if(pending){setDraft(pending);draftText.current=pending;localDraft('new:inbox',pending);queueDraft('new:inbox',pending,null)}else await loadDraft('new:'+(initialProject||'inbox'))}else await loadDraft('new:inbox')}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false;if(draftTimer.current)clearTimeout(draftTimer.current)}},[]);
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('invite'))setNotice('Sign in with your invited email. Your invitation appears in the sidebar; choose Join project to accept.')},[]);
 useEffect(()=>{if(projectId){const q=new URLSearchParams({project:projectId,view:teamOpen?'board':tab==='document'?'documents':'chat'});window.history.replaceState(null,'','?'+q)}},[projectId,teamOpen,tab]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'stage_chat_message',description:'Place a draft in the visible composer for review; does not send it.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:20000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(value:{text?:unknown})=>{if(typeof value.text!=='string'||value.text.length>20000)throw new Error('Text must be under 20,000 characters');updateDraft(value.text);return {staged:true}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[scope]);
 function login(){try{sessionStorage.setItem("recoord:signin-draft",draftText.current)}catch{}window.location.assign(signIn)}
 function discard(){return !dirty||confirm('Discard your unsaved document edits?')}
 async function switchProject(id:string|null){if(busy||loading||!discard())return;await flushDraft();const version=++loadVersion.current;setLoading(true);setError('');try{const next=user?await api<Snapshot>('/api/workspace'+(id?'?project='+id:'')):empty;if(version!==loadVersion.current)return;setData(next);setProjectId(id);setChatOnly(false);setTeamOpen(!!id);window.history.replaceState(null,'',id?'?project='+encodeURIComponent(id):'/');setTeamDocument(undefined);setConversationId(null);setMessages([]);setEditor(null);setDirty(false);setSample(false);setTab('chat');setSidebar(false);await loadDraft('new:'+(id||'inbox'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function newChat(){if(busy||loading)return;setChatOnly(true);setTeamOpen(false);await flushDraft();setConversationId(null);setMessages([]);setSample(false);await loadDraft('new:'+(projectId||'inbox'));setTab('chat');input.current?.focus()}
 async function openConversation(id:string){if(busy||loading)return;setChatOnly(true);setTeamOpen(false);await flushDraft();setLoading(true);setError('');try{const value=await api<Message[]>('/api/messages?id='+id);setConversationId(id);setMessages(value);setSample(false);await loadDraft(id);setSidebar(false);setTab('chat')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 function openProjectForm(index?:number){if(!user){login();return}setEditingProject(false);setFormTitle('');setFormGoal(index===undefined?'':journeys[index].goal);setFormContext('');setProjectForm(true)}
 function editProject(){if(!project)return;setEditingProject(true);setFormTitle(project.title);setFormGoal(project.goal);setFormContext(project.context);setProjectForm(true)}
 async function saveProject(){setFormBusy(true);setError('');try{const id=editingProject?projectId!:crypto.randomUUID();await api('/api/workspace',editingProject?'PATCH':'POST',{kind:'project',id,title:formTitle,goal:formGoal,context:formContext});setProjectForm(false);if(editingProject)await refresh();else await switchProject(id)}catch(e){setError((e as Error).message)}finally{setFormBusy(false)}}
 function showSample(){if(!discard())return;setSample(true);setEditor(null);setDirty(false);setTab('chat');setMessages([{id:'example-user',role:'user',content:'Help me plan a small business website launch.'},{id:'example-assistant',role:'assistant',content:'# Website launch plan\n\n**Goal:** Publish a clear, useful website in two weeks.\n\n## Week 1 — Shape the essentials\n- Define your audience and the action visitors should take.\n- Draft the home, services, and contact pages.\n- Gather your logo, photos, and business details.\n\n## Week 2 — Build and check\n- Build the pages and connect your domain.\n- Test the mobile experience and contact form.\n- Ask three people to review it before launch.\n\n## Next three actions\n1. Write your one-sentence value proposition.\n2. List your three main services.\n3. Choose a launch date.\n\n**Open question:** Who will maintain the website after launch?'}])}
 async function createDocument(content=''){if(!user){login();return}if(project?.role==='viewer'){setNotice('Viewer access: shared documents are read-only.');return}if(!projectId){setNotice('Create or select a project before saving a document.');return}if(!discard())return;setEditor({id:crypto.randomUUID(),project:projectId,title:'Untitled document',content,version:0});setDirty(true);setTeamOpen(false);setTab('document');setNotice('Review your document, give it a title, then save.')}
 async function saveDocument(){if(!editor)return;setSaving(true);setError('');const snapshot={...editor};try{if(!snapshot.version){await api('/api/workspace','POST',{...snapshot,kind:'document'});setEditor({...snapshot,version:1})}else{const saved=await api<{version:number}>('/api/workspace','PATCH',{...snapshot,kind:'document'});setEditor({...snapshot,version:saved.version})}setDirty(false);setNotice('Document saved.');await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function deleteItem(kind:'project'|'document'|'conversation',id:string,title:string){if(busy||saving||!confirm(`Delete “${title}”? ${kind==='project'?'Its conversations, documents, and drafts will also be removed. ':''}This cannot be undone.`))return;await flushDraft();try{if(kind==='conversation')await api('/api/conversations?id='+id,'DELETE');else await api('/api/workspace','DELETE',{kind,id});if(kind==='project'){try{Object.keys(sessionStorage).filter(k=>k.startsWith('recoord:draft:'+user?.id+':')).forEach(k=>sessionStorage.removeItem(k))}catch{}setDirty(false);setProjectId(null);setConversationId(null);setEditor(null);setMessages([]);setData(await api('/api/workspace'));await loadDraft('new:inbox')}else{if(kind==='document'&&editor?.id===id){setEditor(null);setDirty(false)}if(kind==='conversation'&&conversationId===id){localDraft(id,'');setConversationId(null);setMessages([]);await loadDraft('new:'+(projectId||'inbox'))}await refresh()}setNotice('Deleted.')}catch(e){setError((e as Error).message)}}
 async function exportData(projectOnly=false){try{const value=await api('/api/export'+(projectOnly&&projectId?'?project='+projectId:''));download(projectOnly?'recoord-project.json':'recoord-workspace.json',JSON.stringify(value,null,2),'application/json')}catch(e){setError((e as Error).message)}}
 async function deleteAll(){if(deleteText!=='DELETE MY DATA')return;await flushDraft();try{await api('/api/data','DELETE',{confirm:deleteText});try{Object.keys(sessionStorage).filter(k=>k.startsWith('recoord:draft:'+user?.id+':')).forEach(k=>sessionStorage.removeItem(k))}catch{}setData(empty);setProjectId(null);setConversationId(null);setMessages([]);setEditor(null);setDirty(false);setDraft('');draftText.current='';setDeleteText('');setSettings(false);setNotice('Your saved Recoord content has been deleted. Your sign-in account is unchanged.')}catch(e){setError((e as Error).message)}}
 async function send(){if(busy||loading||!draft.trim())return;if(!user){login();return}if(!ready){setError('This preview has no AI provider connected. Your draft is saved; projects and documents still work.');return}await flushDraft();const id=conversationId||crypto.randomUUID(),content=draft.trim(),submission=requestId.current||crypto.randomUUID();requestId.current=submission;const previous=sample?[]:messages;setSample(false);setBusy(true);setError('');setMessages([...previous,{id:submission,role:'user',content},{id:submission+':reply',role:'assistant',content:''}]);let accepted=false,done=false;
 try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,project:projectId,requestId:submission,content,draftScope:scope})});if(!r.ok){const value=await r.json() as {error:string};throw new Error(value.error)}accepted=true;setConversationId(id);setDraft('');draftText.current='';localDraft(scope,'');setDraftStatus('');const reader=r.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const chunk=await reader.read();buffer+=chunk.done?decoder.decode():decoder.decode(chunk.value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';if(chunk.done&&buffer)lines.push(buffer);for(const line of lines){if(!line)continue;const value=JSON.parse(line);if(value.delta)setMessages(m=>m.map(x=>x.id===submission+':reply'?{...x,content:x.content+value.delta}:x));if(value.done)done=true;if(value.error)throw new Error(value.error)}if(chunk.done)break}if(!done)throw new Error('The connection was interrupted. Reopen the conversation to check the saved reply.');requestId.current=null;await refresh()}catch(e){setError((e as Error).message);if(!accepted)setMessages(previous);else{setMessages(m=>m.map(x=>x.id===submission+':reply'?{...x,content:x.content+'\n\n[Incomplete reply — check saved conversation.]'}:x));await refresh().catch(()=>{})}}finally{setBusy(false)}}
 return <div className="app"><aside className={'sidebar '+(sidebar?'open':'')}><a className="brand" href="/" aria-label="Recoord home"><img className="brand-symbol" src="/recoord-mark.svg" alt="" width={36} height={36}/><span className="brand-wordmark">recoord</span></a><button className="new" onClick={()=>openProjectForm()} disabled={busy}><Plus size={18}/>New project</button><p className="eyebrow">YOUR WORKSPACE</p><button className={'nav-item '+(!projectId?'selected':'')} onClick={()=>switchProject(null)}><MessageSquare size={17}/>Workspace</button>{user&&<Invitations joined={id=>void switchProject(id)}/>}<div className="project-list">{data.projects.map(p=><button className={'nav-item '+(projectId===p.id?'selected':'')} key={p.id} onClick={()=>switchProject(p.id)} disabled={busy}><Folder size={17}/><span>{p.title}</span><small className="project-role">{p.role==='owner'?'':p.role}</small></button>)}{!data.projects.length&&<p className="empty-note">A place for your goals,<br/>conversations, and drafts.</p>}</div><p className="eyebrow">PRIVATE CONVERSATIONS</p><div className="history">{data.conversations.map(c=><div className={'history-item '+(conversationId===c.id?'selected':'')} key={c.id}><button disabled={busy||loading} onClick={()=>openConversation(c.id)}><MessageSquare size={14}/><span>{c.title}</span></button><button aria-label={'Delete '+c.title} onClick={()=>deleteItem('conversation',c.id,c.title)}><Trash2 size={13}/></button></div>)}</div><div className="sidebar-bottom"><a className="source-note" href="https://github.com/alhajahmad/Recoord" target="_blank" rel="noreferrer"><Leaf size={16}/>Open source · GitHub</a><button className="nav-item" onClick={()=>setSettings(true)}><Settings2 size={17}/>Settings & data</button>{user?<div className="account"><span className="avatar">{user.name[0].toUpperCase()}</span><div><span>{user.name}</span><button onClick={async()=>{if(!discard())return;await flushDraft();try{Object.keys(sessionStorage).filter(k=>k.startsWith('recoord:draft:'+user.id+':')).forEach(k=>sessionStorage.removeItem(k))}catch{}window.location.assign(signOut)}}>Sign out</button></div></div>:<button className="sign-in" onClick={login}>Sign in with ChatGPT</button>}</div></aside>{sidebar&&<button className="scrim" aria-label="Close menu" onClick={()=>setSidebar(false)}/>}
 <main><header><div className="header-title"><button className="icon mobile" aria-label="Open menu" onClick={()=>setSidebar(true)}><Menu size={20}/></button><span className="breadcrumb">Workspace /</span><strong>{project?.title||data.conversations.find(c=>c.id===conversationId)?.title||(user?'Your workspace':'Recoord')}</strong></div><div className="header-actions"><span className="connection-status"><i className={ready?'online':''}/>{ready?'AI ready':'Preview'}</span>{project&&<button className="icon" aria-label="Project settings" onClick={editProject}><Settings2 size={18}/></button>}<button className="small-button" disabled={busy||loading} onClick={newChat}><Plus size={16}/>New chat</button></div></header>
 {project&&<div className="project-navigation"><div role="tablist" aria-label="Project views"><button role="tab" aria-selected={teamOpen} onClick={()=>{setTeamDocument(undefined);setTeamOpen(true)}}><ListChecks size={16}/>Project board</button><button role="tab" aria-selected={!teamOpen&&tab==='chat'} onClick={()=>{setTeamOpen(false);setTab('chat')}}><MessageSquare size={16}/>Private chat</button><button role="tab" aria-selected={!teamOpen&&tab==='document'} onClick={()=>{setTeamOpen(false);setTab('document')}}><FileText size={16}/>Documents <span>{data.documents.length}</span></button></div><button className="icon" aria-label="Export project" onClick={()=>exportData(true)}><Download size={16}/></button></div>}

 {(error||notice)&&<div className={error?'error-banner':'notice-banner'} role={error?'alert':'status'}><span>{error||notice}</span><button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('')}}><X size={16}/></button></div>}

 {project&&teamOpen&&<Team key={project.id+':'+(teamDocument||'')} project={project.id} user={user!.id} title={project.title} goal={project.goal} initialDocument={teamDocument}/>}<div style={teamOpen?{display:'none'}:undefined} className={'work-area '+(projectId?'with-project ':'')+(projectId&&tab==='document'?'documents-view':'')}><section className={'chat-column '+(projectId&&tab==='document'?'view-hidden':'')}>
 {!messages.length&&user&&!projectId&&!chatOnly&&data.projects.length>0?<div className="workspace-home"><span className="kicker">YOUR WORK, TOGETHER</span><h1>Pick up where you left off.</h1><p>Open a project to see the plan, people, and next steps.</p><div className="project-cards">{data.projects.map(p=><button key={p.id} onClick={()=>void switchProject(p.id)}><span className="project-card-icon"><Folder size={22}/></span><strong>{p.title}</strong><p>{p.goal||'A shared place for your next idea.'}</p><span className="project-card-footer">{p.role}<span>Open project →</span></span></button>)}<button className="new-project-card" onClick={()=>openProjectForm()}><Plus size={25}/><strong>Start a project</strong><p>Give your team a clear goal.</p></button></div><div className="workspace-tip"><MessageSquare size={18}/><span>Need to think something through?</span><button className="small-button" onClick={newChat}>Start a private chat</button></div></div>:!messages.length?<div className="welcome"><span className="kicker">FROM A FIRST THOUGHT TO A FINISHED THING</span><h1>{project?'Let’s move this forward.':<>Turn ideas into work<br/>you can return to.</>}</h1><p>{project?'Your AI chats are private. Saved project documents are shared with teammates.':'Give your work a home. Make a plan, shape a draft, or work through a decision.'}</p><div className="journeys">{journeys.map((j,i)=><button key={j.name} onClick={()=>{if(project)updateDraft(j.prompt);else openProjectForm(i)}}><j.icon size={22}/><strong>{j.name}</strong><span>{i===0?'Find your next steps':i===1?'Get the first version down':'See the tradeoffs clearly'}</span></button>)}</div><button className="sample-link" onClick={showSample}>Explore a sample project</button></div>:<div className="messages" aria-label="Conversation">{sample&&<div className="sample-label">Sample conversation · written example, not a live AI response</div>}{messages.map(m=><article className={'message '+m.role} key={m.id}><div className="message-label">{m.role==='user'?'You':'Recoord'}</div><RichText text={m.content}/>{busy&&!m.content&&<span className="thinking">Working on it…</span>}{m.content&&<div className="message-actions"><button aria-label="Copy message" onClick={async()=>{try{await navigator.clipboard.writeText(m.content);setCopied(m.id)}catch{setError('Copy isn’t available. Select the text to copy it.')}}}>{copied===m.id?<Check size={14}/>:<Copy size={14}/>}Copy</button>{m.role==='assistant'&&<button onClick={()=>createDocument(m.content)}><FileText size={14}/>Save as document</button>}</div>}</article>)}<div ref={bottom}/></div>}
 <div className="compose-area" style={user&&!projectId&&!chatOnly&&!messages.length&&data.projects.length?{display:'none'}:undefined}>{!ready&&<div className="readiness">Preview · AI replies aren’t connected yet. {user?'Your projects and documents are ready to use.':'Sign in to save projects and documents.'}</div>}<form className="composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea ref={input} aria-label="Message Recoord" placeholder={project?'What would you like to work on?':'Start with an idea, a question, or an outcome…'} value={draft} maxLength={20000} onChange={e=>updateDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><div className="compose-footer"><div className="compose-tools"><input ref={file} hidden type="file" accept=".txt,.md,.csv,.json,.js,.ts,.py" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>16000){setError('Choose a text file under 16 KB.');return}const next=draft+'\n\nReference: '+f.name+'\n'+await f.text();if(next.length>20000){setError('Message and attachment must fit within 20,000 characters.');return}updateDraft(next)}}/><button type="button" className="icon" aria-label="Attach text file" onClick={()=>file.current?.click()}><Paperclip size={18}/></button><button className="model-label" type="button" onClick={()=>setSettings(true)}>{ready?model:'No model connected'}</button></div><button className="send" aria-label="Send message" disabled={busy||loading||!draft.trim()}><Send size={18}/></button></div></form><div className="compose-note"><span>{draftStatus||'Enter to send · Shift + Enter for a new line'}</span><span>AI can make mistakes.</span></div></div>
 </section>{project&&<aside className={'document-panel '+(tab==='chat'?'view-hidden':'')}><div className="panel-heading"><h2><FileText size={18}/>Shared documents</h2><button className="icon" aria-label="New document" onClick={()=>createDocument()}><Plus size={18}/></button></div><div className="document-list">{data.documents.map(d=><button className={editor?.id===d.id?'selected':''} key={d.id} onClick={()=>{if(discard()){setEditor({...d});setDirty(false)}}}><FileText size={15}/><span>{d.title}</span></button>)}</div>{editor?<div className="editor"><label className="sr-only" htmlFor="document-title">Document title</label><input id="document-title" value={editor.title} maxLength={100} disabled={saving||project?.role==='viewer'} onChange={e=>{setEditor({...editor,title:e.target.value});setDirty(true)}}/><button className="small-button" onClick={()=>{setTeamDocument(editor.id);setTeamOpen(true)}} disabled={!editor.version}>Discussion</button><div className="editor-status" role="status">{saving?'Saving…':dirty?'Unsaved changes':'Saved'} · Markdown supported</div><textarea aria-label="Document content" value={editor.content} maxLength={100000} disabled={saving||project?.role==='viewer'} onChange={e=>{setEditor({...editor,content:e.target.value});setDirty(true)}}/><div className="editor-actions"><button className="primary" disabled={saving||project?.role==='viewer'||!editor.title.trim()||!dirty} onClick={saveDocument}><Save size={15}/>Save</button><button className="small-button" onClick={()=>download(editor.title.replace(/[^a-z0-9 -]/gi,'').slice(0,60)+'.md',editor.content)}><Download size={15}/>Export</button>{editor.version>0&&project?.role!=='viewer'&&<button className="icon" aria-label="Delete document" onClick={()=>deleteItem('document',editor.id,editor.title)}><Trash2 size={16}/></button>}</div></div>:<div className="document-empty"><FileText size={30}/><h3>A result worth keeping.</h3><p>Save an answer as a document, or start your own. Edit it here and pick up where you left off.</p><button className="small-button" onClick={()=>createDocument()}>Create a document</button></div>}</aside>}</div></main>
 <Dialog open={projectForm} onOpenChange={v=>{if(!formBusy)setProjectForm(v)}}><DialogContent className="recoord-dialog"><DialogTitle>{editingProject?'Project settings':'Give your work a home'}</DialogTitle><DialogDescription>Keep a goal, useful context, and finished work together.</DialogDescription><form onSubmit={e=>{e.preventDefault();void saveProject()}}><label>Project name<input value={formTitle} maxLength={100} required onChange={e=>setFormTitle(e.target.value)} placeholder="e.g. Launch my business website"/></label><label>What do you want to achieve?<textarea value={formGoal} maxLength={4000} onChange={e=>setFormGoal(e.target.value)} placeholder="A specific outcome makes a useful starting point."/></label><label>Reference context<textarea value={formContext} maxLength={16000} onChange={e=>setFormContext(e.target.value)} placeholder="Background, requirements, or notes the assistant should use."/></label><p className="form-hint">This context is sent to the model with each message in this project. Edit or remove it anytime.</p><input ref={contextFile} type="file" hidden accept=".txt,.md,.csv,.json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const next=formContext+'\n\n'+f.name+'\n'+await f.text();if(f.size>16000||next.length>16000){setError('Project context must fit within 16,000 characters.');return}setFormContext(next)}}/><button type="button" className="small-button" onClick={()=>contextFile.current?.click()}><Paperclip size={15}/>Add text file</button>{error&&<p role="alert" className="form-error">{error}</p>}<div className="dialog-actions">{editingProject&&project?.role==='owner'&&<button type="button" className="danger" onClick={async()=>{await deleteItem('project',projectId!,formTitle);setProjectForm(false)}}>Delete project</button>}<button className="primary" disabled={formBusy||!formTitle.trim()||(editingProject&&project?.role==='viewer')}>{formBusy?'Saving…':editingProject?'Save changes':'Create project'}</button></div></form></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="recoord-dialog"><DialogTitle>Settings & your data</DialogTitle><DialogDescription>Know what powers your workspace and control what you keep.</DialogDescription><div className="settings-section"><h3>AI connection</h3><p><strong>{ready?provider:'Not connected'}</strong>{ready?' · '+model:''}</p><p>{ready?'Messages, recent conversation history, and project context are sent to this provider when you ask for a reply.':'AI responses are unavailable until the site owner connects a provider. No sample text is presented as a live reply.'}</p><p>Saved content is stored on our hosting service. Open-source code does not mean messages stay on your device.</p></div><div className="settings-section"><h3>Your saved work</h3><p>Export includes accessible shared work and your private conversations. Deleting your data deletes projects you own for everyone and removes your memberships. Contributions to other people’s projects remain, attributed to a former member. Your ChatGPT account is unchanged; daily usage counters remain.</p><button className="small-button" disabled={!user} onClick={()=>exportData()}><Download size={16}/>Export all saved work</button><label>To delete all saved Recoord content, type DELETE MY DATA<input value={deleteText} onChange={e=>setDeleteText(e.target.value)} placeholder="DELETE MY DATA"/></label><button className="danger" disabled={!user||deleteText!=='DELETE MY DATA'} onClick={deleteAll}>Delete my saved content</button></div><div className="settings-section"><h3>Open source</h3><p>MIT-licensed application. Model licensing and provider charges are separate.</p><a href="/recoord-source.zip" download>Download source & self-hosting guide</a></div>{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
 </div>
}
