'use client';
import {useRef} from 'react';
import {ArrowUp,ArrowRight,LockKeyhole,PenLine,ListChecks,Compass,Plus} from 'lucide-react';
type Props={draft:string;onDraft:(text:string)=>void;onSend:()=>void;onContinue:()=>void;onCreate:()=>void;onConnection:()=>void;ready:boolean;preview:boolean;busy:boolean;draftStatus:string};
const starters=[{label:'Make a plan',icon:ListChecks,prompt:'Help me turn an idea into a practical plan. Start by asking what I want to achieve and when.'},{label:'Write a first draft',icon:PenLine,prompt:'Help me write a first draft. Ask about the audience, purpose, and format before you start.'},{label:'Compare options',icon:Compass,prompt:'Help me compare my options. Ask what decision I need to make and what matters most to me.'}];
export default function HomeStart(p:Props){const input=useRef<HTMLTextAreaElement>(null);function submit(){if(p.busy||!p.draft.trim())return;if(p.ready)p.onSend();else p.onContinue()}
 return <section className="home-start" aria-labelledby="home-start-title"><div className="home-start-heading"><div><span className="home-label">Your workspace</span><h1 id="home-start-title">What’s your next move?</h1><p>Think it through with AI, or give it a home in a project.</p></div><button className="home-project-action" onClick={p.onCreate} disabled={p.busy}><Plus size={16}/>Create project</button></div>
 <form className="home-prompt" onSubmit={e=>{e.preventDefault();submit()}}><textarea ref={input} aria-label="Start a private AI conversation" value={p.draft} maxLength={20000} disabled={p.busy} placeholder="Describe an idea, ask a question, or tell Recoord what you want to get done…" onChange={e=>p.onDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit()}}}/><div className="home-prompt-footer"><span><LockKeyhole size={13}/>Private conversation</span><button className="home-send" disabled={p.busy||!p.draft.trim()}>{p.busy?'Starting…':p.ready?'Start chat':'Continue in chat'}{p.ready?<ArrowUp size={16}/>:<ArrowRight size={16}/>}</button></div></form>
 <div className="home-starters" aria-label="Conversation starters">{starters.map(s=><button key={s.label} disabled={p.busy} onClick={()=>{p.onDraft(s.prompt);input.current?.focus()}}><s.icon size={15}/>{s.label}</button>)}</div>
 <div className="home-start-note"><span role="status">{p.draftStatus||(p.ready?'Enter to send · Shift + Enter for a new line':'AI replies need a connected provider. You can still prepare a draft.')}</span>{!p.ready&&<button onClick={p.onConnection}>{p.preview?'Local preview · AI not connected':'Set up AI'}<ArrowRight size={12}/></button>}</div>
 </section>
}
