'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,Plus,Search,Users} from 'lucide-react';
import './admin-tools.css';
type Project={id:string;title:string;role:string};type Member={id:string;name:string;email:string;role:string};type Invite={id:string;email:string;role:string;created:number};type Group={id:string;name:string;description:string;memberIds:string[]};type Team={role:string;members:Member[];invitations:Invite[]};
async function api<T>(url:string,init?:RequestInit):Promise<T>{const res=await fetch(url,{...init,headers:{'Content-Type':'application/json',...init?.headers}});const value=await res.json() as T&{error?:string};if(!res.ok)throw new Error(value.error||'Could not complete this request.');return value}
export default function PeopleControls({projects,onChanged}:{projects:Project[];onChanged:()=>void}){
 const [project,setProject]=useState(projects[0]?.id||''),[tab,setTab]=useState('members'),[team,setTeam]=useState<Team|null>(null),[groups,setGroups]=useState<Group[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[refresh,setRefresh]=useState(0),[email,setEmail]=useState(''),[role,setRole]=useState('viewer');
 const [editor,setEditor]=useState<Group|null>(null);const lock=useRef(false);
 useEffect(()=>{if(!projects.some(p=>p.id===project))setProject(projects[0]?.id||'')},[projects,project]);
 useEffect(()=>{setTeam(null);setGroups([]);setEditor(null);setError('');setMessage('');if(!project)return;const c=new AbortController();setLoading(true);Promise.all([api<Team>(`/api/team?project=${encodeURIComponent(project)}`,{signal:c.signal}),api<{groups:Group[]}>(`/api/groups?project=${encodeURIComponent(project)}`,{signal:c.signal})]).then(([t,g])=>{setTeam(t);setGroups(g.groups)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[project,refresh]);
 async function mutate(url:string,payload:object,method='POST',notice='Changes saved.'){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await api(url,{method,body:JSON.stringify({project,...payload})});const [t,g]=await Promise.all([api<Team>(`/api/team?project=${encodeURIComponent(project)}`),api<{groups:Group[]}>(`/api/groups?project=${encodeURIComponent(project)}`)]);setTeam(t);setGroups(g.groups);setEditor(null);setEmail('');setMessage(notice);onChanged()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false);lock.current=false}}
 async function leave(){if(lock.current||!window.confirm('Leave this project? You will lose access until invited again.'))return;lock.current=true;setBusy(true);setError('');try{await api('/api/team',{method:'POST',body:JSON.stringify({project,action:'leave'})});setTeam(null);setProject('');onChanged()}catch(e){setError(e instanceof Error?e.message:'Could not leave project.')}finally{setBusy(false);lock.current=false}}
 function exportMembers(){if(!team)return;const cell=(v:string)=>'"'+(/^[\s]*[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';const csv=['Name,Email,Role',...team.members.map(m=>[m.name,m.email,m.role].map(cell).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='recoord-project-members.csv';a.click();URL.revokeObjectURL(url);setMessage('Member list downloaded.')}
 const owner=team?.role==='owner';const members=team?.members.filter(m=>(m.name+' '+m.email+' '+m.role).toLowerCase().includes(query.toLowerCase().trim()))||[];
 return <div className="people-controls">{!projects.length?<p className="admin-empty">Join or create a project to manage people.</p>:<><label className="admin-tool-project">Project<select disabled={busy} value={project} onChange={e=>{if(editor&&!window.confirm('Discard this group draft?'))return;setProject(e.target.value)}}>{projects.map(p=><option key={p.id} value={p.id}>{p.title} · {p.role}</option>)}</select></label><div className="admin-tool-tabs" role="tablist" aria-label="People and permissions">{['members','invitations','groups','roles'].map(v=><button key={v} role="tab" aria-selected={tab===v} onClick={()=>setTab(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>{loading&&<p className="admin-muted" role="status">Loading project people…</p>}{error&&<div className="admin-error" role="alert">{error}<button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>}{message&&<p className="admin-success" role="status">{message}</p>}{team&&<div role="tabpanel" aria-label={tab}>
 {tab==='members'&&<><div className="people-toolbar"><label className="people-search"><Search size={14}/><input placeholder="Search name, email, or role" aria-label="Search members" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="admin-button" onClick={exportMembers}><Download size={14}/>Export CSV</button></div><p className="admin-muted">{team.members.length} project {team.members.length===1?'member':'members'}. {owner?'You can change editor and viewer access.':'Only the owner can change access.'}</p><div className="people-members">{members.map(m=><div className="people-member" key={m.id}><span className="people-initial">{m.name.slice(0,1).toUpperCase()}</span><div><strong>{m.name}</strong><small>{m.email}</small></div>{owner&&m.role!=='owner'?<><select aria-label={`Role for ${m.name}`} value={m.role} disabled={busy} onChange={e=>{const next=e.target.value;if(window.confirm(`Change ${m.name} to ${next}?`))void mutate('/api/team',{action:'role',user:m.id,role:next})}}><option value="viewer">Viewer</option><option value="editor">Editor</option></select><button className="people-remove" disabled={busy} onClick={()=>{if(window.confirm(`Remove ${m.name} from this project?`))void mutate('/api/team',{action:'remove',user:m.id},'POST','Member removed.')}}>Remove</button></>:<span className="admin-role">{m.role}</span>}</div>)}</div>{!members.length&&<p className="admin-empty">No matching members.</p>}{!owner&&<div className="people-leave"><p>Your contributions remain in the project after you leave.</p><button className="admin-button admin-danger" disabled={busy} onClick={()=>void leave()}>Leave project</button></div>}</>}
 {tab==='invitations'&&<>{owner?<><p className="admin-intro">Invite someone using their sign-in email. Invitations appear inside Recoord; no email is sent. Invitations expire after seven days.</p><form className="people-invite" onSubmit={e=>{e.preventDefault();void mutate('/api/team',{action:'invite',email,role},'POST','In-app invitation created.')}}><label>Email address<input type="email" required maxLength={254} placeholder="teammate@example.com" value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} disabled={busy} onChange={e=>setRole(e.target.value)}><option value="viewer">Viewer</option><option value="editor">Editor</option></select></label><button className="admin-button admin-primary" disabled={busy||!email.trim()}>Invite member</button></form><div className="people-invitations">{team.invitations.length?team.invitations.map(v=><div className="people-member" key={v.id}><div><strong>{v.email}</strong><small>{v.role} · {v.created+7*86400000<Date.now()?'Expired':'Expires '+new Date(v.created+7*86400000).toLocaleDateString()}</small></div><button className="admin-button" disabled={busy} onClick={()=>{if(window.confirm('Revoke this invitation?'))void mutate('/api/team',{action:'revoke',id:v.id},'POST','Invitation revoked.')}}>Revoke</button></div>):<p className="admin-empty">No invitations yet.</p>}</div></>:<p className="admin-empty">Only the project owner can view and manage invitations.</p>}</>}
 {tab==='groups'&&<><p className="admin-intro">Organize project members into teams. Groups do not grant permissions, create chats, or change project roles.</p>{owner&&<button className="admin-button" disabled={busy||!!editor} onClick={()=>setEditor({id:'',name:'',description:'',memberIds:[]})}><Plus size={14}/>New group</button>}{editor&&<form className="people-group-editor" onSubmit={e=>{e.preventDefault();void mutate('/api/groups',editor,editor.id?'PATCH':'POST','Group saved.')}}><label>Group name<input required maxLength={80} value={editor.name} disabled={busy} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label>Description<textarea maxLength={300} value={editor.description} disabled={busy} onChange={e=>setEditor({...editor,description:e.target.value})}/></label><fieldset disabled={busy}><legend>Group members ({editor.memberIds.length}/100)</legend>{team.members.map(m=><label className="people-checkbox" key={m.id}><input type="checkbox" checked={editor.memberIds.includes(m.id)} disabled={!editor.memberIds.includes(m.id)&&editor.memberIds.length>=100} onChange={e=>setEditor({...editor,memberIds:e.target.checked?[...editor.memberIds,m.id]:editor.memberIds.filter(id=>id!==m.id)})}/><span>{m.name}<small>{m.role}</small></span></label>)}</fieldset><div className="people-form-actions"><button className="admin-button admin-primary" disabled={busy||!editor.name.trim()}>Save group</button><button type="button" className="admin-button" disabled={busy} onClick={()=>setEditor(null)}>Cancel</button></div></form>}<div className="people-group-list">{groups.map(g=><article key={g.id}><span className="people-initial"><Users size={17}/></span><div><strong>{g.name}</strong>{g.description&&<p>{g.description}</p>}<small>{g.memberIds.length} members</small><p className="people-group-names">{g.memberIds.map(id=>team.members.find(m=>m.id===id)?.name).filter(Boolean).join(', ')||'No members assigned'}</p></div>{owner&&<div className="people-group-actions"><button className="admin-button" disabled={busy} onClick={()=>{if(editor&&!window.confirm('Discard this group draft?'))return;setEditor({...g,memberIds:[...g.memberIds]})}}>Edit</button><button className="people-remove" disabled={busy} onClick={()=>{if(window.confirm(`Delete ${g.name}? Project memberships stay unchanged.`))void mutate('/api/groups',{id:g.id},'DELETE','Group deleted.')}}>Delete</button></div>}</article>)}</div>{!groups.length&&!editor&&<p className="admin-empty">No groups yet.</p>}</>}
 {tab==='roles'&&<><p className="admin-intro">Three fixed project roles. Groups are organizational and never override these permissions.</p><div className="people-role-table"><table><thead><tr><th scope="col">Permission</th><th scope="col">Owner</th><th scope="col">Editor</th><th scope="col">Viewer</th></tr></thead><tbody>{[['Read shared project content',true,true,true],['Create and edit shared work',true,true,false],['Manage invitations and roles',true,false,false],['Manage organizational groups',true,false,false],['Change project policies',true,false,false],['Create and revoke API keys',true,false,false],['Delete the project',true,false,false]].map(([label,...values])=><tr key={String(label)}><th scope="row">{label}</th>{values.map((v,i)=><td key={i}>{v?'Allowed':'—'}</td>)}</tr>)}</tbody></table></div><p className="admin-muted">Tool availability and activity visibility also follow the project’s saved policies. Custom roles and owner transfer are not currently available.</p></>}
 </div>}</>}</div>
}
