'use client';
import {useMemo,useState} from 'react';
import {Search,Plus,ArrowRight,Folder,FileText,Users,ListChecks,LayoutGrid,List,X} from 'lucide-react';
export type ProjectSummary={id:string;title:string;goal:string;role:'owner'|'editor'|'viewer';updated?:number;lastActivity?:number;taskCount?:number;completedCount?:number;documentCount?:number;memberCount?:number};
export default function ProjectGrid({projects,onOpen,onCreate,disabled=false,view,onViewChange:setView}:{view:'grid'|'list';onViewChange:(view:'grid'|'list')=>void;projects:ProjectSummary[];onOpen:(id:string)=>void;onCreate:()=>void;disabled?:boolean}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('recent');
 const visible=useMemo(()=>projects.filter(p=>(filter==='all'||filter==='owned'&&p.role==='owner'||filter==='shared'&&p.role!=='owner')&&(p.title+' '+p.goal).toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):((b.lastActivity||b.updated||0)-(a.lastActivity||a.updated||0))),[projects,query,filter,sort]);
 function updated(p:ProjectSummary){const timestamp=p.lastActivity||p.updated;if(!timestamp)return 'Ready to start';const d=new Date(timestamp),days=Math.floor((new Date().setHours(0,0,0,0)-new Date(timestamp).setHours(0,0,0,0))/86400000);return days<=0?'Updated today':days===1?'Updated yesterday':'Updated '+d.toLocaleDateString(undefined,{month:'short',day:'numeric',...(d.getFullYear()!==new Date().getFullYear()?{year:'numeric'}:{})})}
 return <section className="project-library" aria-labelledby="project-library-title"><div className="library-heading"><div><h2 id="project-library-title">Projects <span>{projects.length}</span></h2><p>Your plans, progress, and shared work.</p></div><button className="small-button" disabled={disabled} onClick={onCreate}><Plus size={15}/>New project</button></div>
 <div className="library-toolbar"><label className="library-search"><Search size={16}/><input aria-label="Find projects" placeholder="Find a project…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear project search" onClick={()=>setQuery('')}><X size={14}/></button>}</label><select aria-label="Filter projects" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All projects</option><option value="owned">Created by you</option><option value="shared">Shared with you</option></select><select aria-label="Sort projects" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently active</option><option value="name">Name A–Z</option></select><div className="library-view" role="group" aria-label="Project layout"><button aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={16}/></button><button aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={17}/></button></div></div>
 {(query||filter!=='all')&&<p className="library-result" role="status">{visible.length} of {projects.length} projects</p>}
 <div className={'project-library-cards '+(view==='list'?'is-list':'')}>{visible.map(p=>{const total=p.taskCount??0,complete=p.completedCount??0,docs=p.documentCount??0,people=p.memberCount??1;return <button className="project-tile" key={p.id} disabled={disabled} aria-label={'Open project: '+p.title} onClick={()=>onOpen(p.id)}><div className="tile-top"><span className="tile-icon"><Folder size={21}/></span><span className={'tile-access '+(p.role==='viewer'?'is-viewer':'')}>{p.role==='owner'?'Your project':p.role==='editor'?'Can edit':'View only'}</span><ArrowRight className="tile-arrow" size={17}/></div><div className="tile-content"><h3>{p.title}</h3><p>{p.goal||'Add a project goal to give your work a clear direction.'}</p></div><div className="tile-progress"><div><span><ListChecks size={14}/>{total?`${complete} of ${total} ${total===1?'task':'tasks'} done`:'No tasks yet'}</span><span>{total?Math.round(complete/total*100)+'%':'Ready to plan'}</span></div>{total>0&&<progress aria-label={p.title+' task completion'} max={total} value={complete}/>}</div><div className="tile-footer"><span title={docs+' documents'}><FileText size={13}/>{docs} {docs===1?'document':'documents'}</span><span title={people+' members'}><Users size={14}/>{people}</span><time dateTime={p.lastActivity||p.updated?new Date(p.lastActivity||p.updated!).toISOString():undefined}>{updated(p)}</time></div></button>})}</div>
 {!visible.length&&<div className="library-empty"><Search size={27}/><h3>{projects.length?'No matching projects':'Your first project starts here'}</h3><p>{projects.length?'Try a different name or clear your filters.':'Create a project to bring your goals, tasks, and documents together.'}</p><button className="small-button" onClick={()=>{if(projects.length){setQuery('');setFilter('all')}else onCreate()}}>{projects.length?'Clear filters':'Create a project'}</button></div>}
 </section>
}
