'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,Folder,LockKeyhole,RefreshCw,Search,ShieldCheck} from 'lucide-react';
import './project-policy-panel.css';
type Policy={project:string;revision:number;usageVisibility:'owner'|'members';logsVisibility:'hidden'|'owner'|'members';aiEnabled:boolean;importsEnabled:boolean;fileSearchEnabled:boolean;apiEnabled:boolean;auditEnabled:boolean;apiLogMode:'disabled'|'per_call'|'all';inviteDomains:string[];updated:number|null};
type PolicyData={policy:Policy;events:{id:string;actor:string;actorName:string;action:string;details:{changedFields?:string[];status?:number;keyId?:string};created:number}[];role:'owner'|'editor'|'viewer';usage:{day:string;reads:number}|null};
type Props={projects:{id:string;title:string;role:string}[];tab:'visibility'|'tools'|'sharing'|'retention'|'security'};
type SearchResult={id:string;title:string;excerpt:string};
async function api<T>(url:string,init?:RequestInit):Promise<T>{const res=await fetch(url,{...init,headers:{'Content-Type':'application/json',...init?.headers}});const data=await res.json() as T&{error?:string};if(!res.ok)throw new Error(res.status===409?'This policy changed in another session. Reload the latest version before saving.':data.error||'Could not load project controls. Try again.');return data}
function date(n:number|null){return n?new Date(n<1e12?n*1000:n).toLocaleString(): 'Not saved yet'}
function Unavailable({name,children}:{name:string;children:React.ReactNode}){return <div className="policy-unavailable"><div><strong>{name}</strong><span>Not available</span></div><p>{children}</p></div>}
export default function ProjectPolicyPanel({projects,tab}:Props){
 const [project,setProject]=useState(()=>projects.find(p=>p.role==='owner')?.id||projects[0]?.id||''),[data,setData]=useState<PolicyData|null>(null),[draft,setDraft]=useState<Policy|null>(null),[domains,setDomains]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0),[security,setSecurity]=useState('domains');
 const [query,setQuery]=useState(''),[results,setResults]=useState<SearchResult[]|null>(null),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState('');
 const lock=useRef(false),generation=useRef(0),searchController=useRef<AbortController|null>(null);
 const domainList=domains.split(/[\s,]+/).map(v=>v.trim().toLowerCase()).filter(Boolean);
 const dirty=!!data&&!!draft&&(JSON.stringify({...draft,inviteDomains:domainList})!==JSON.stringify(data.policy));
 const editable=data?.role==='owner'&&!loading&&!saving;
 useEffect(()=>{if(!projects.some(p=>p.id===project))setProject(projects.find(p=>p.role==='owner')?.id||projects[0]?.id||'')},[projects,project]);
 useEffect(()=>{generation.current++;const controller=new AbortController();setData(null);setDraft(null);setError('');setMessage('');setResults(null);setQuery('');setSearchError('');setSearching(false);searchController.current?.abort();if(!project)return;setLoading(true);api<PolicyData>(`/api/project-policy?project=${encodeURIComponent(project)}`,{signal:controller.signal}).then(v=>{setData(v);setDraft(v.policy);setDomains(v.policy.inviteDomains.join('\n'))}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>{controller.abort();searchController.current?.abort()}},[project,reload]);
 function change<K extends keyof Policy>(field:K,value:Policy[K]){if(!editable||!draft)return;setDraft({...draft,[field]:value});setMessage('')}
 function selectProject(id:string){if(dirty&&!window.confirm('Discard unsaved project policy changes?'))return;setProject(id)}
 async function save(){if(lock.current||!draft||!editable)return;lock.current=true;setSaving(true);setError('');setMessage('');const current=generation.current;try{const value=await api<PolicyData>('/api/project-policy',{method:'PATCH',body:JSON.stringify({project,policy:{...draft,inviteDomains:domainList}})});if(generation.current===current){setData(value);setDraft(value.policy);setDomains(value.policy.inviteDomains.join('\n'));setMessage('Project controls saved.')}}catch(e){if(generation.current===current)setError(e instanceof Error?e.message:'Could not save project controls.')}finally{setSaving(false);lock.current=false}}
 async function search(){if(!query.trim()||!data?.policy.fileSearchEnabled)return;searchController.current?.abort();const controller=new AbortController();searchController.current=controller;setSearching(true);setSearchError('');setResults(null);try{const value=await api<{results:SearchResult[];limit:number}>(`/api/project-search?project=${encodeURIComponent(project)}&q=${encodeURIComponent(query.trim())}`,{signal:controller.signal});if(!controller.signal.aborted)setResults(value.results)}catch(e){if(!controller.signal.aborted)setSearchError(e instanceof Error?e.message:'Search could not be completed.')}finally{if(!controller.signal.aborted)setSearching(false)}}
 function toggle(field:'aiEnabled'|'importsEnabled'|'fileSearchEnabled'|'apiEnabled'|'auditEnabled',title:string,description:string){return <label className="policy-control"><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={draft?.[field]||false} onChange={e=>change(field,e.target.checked)} disabled={!editable}/></label>}
 return <section className="project-policy-panel" aria-label="Project policy controls"><div className="policy-heading"><span className="policy-symbol"><ShieldCheck size={19}/></span><div><h3>Project controls</h3><p>Settings apply only to the selected project.</p></div></div>{!projects.length?<p className="policy-empty">Create or join a project to view its controls.</p>:<><label className="policy-project-label"><span><Folder size={14}/> Project</span><select value={project} disabled={saving} onChange={e=>selectProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.title} · {p.role}</option>)}</select></label>{loading&&<p className="policy-status" role="status">Loading project policy…</p>}{error&&<div className="policy-error" role="alert"><p>{error}</p><button className="admin-button" disabled={saving} onClick={()=>{if(!dirty||window.confirm('Reload and discard unsaved changes?'))setReload(v=>v+1)}}><RefreshCw size={14}/>Reload latest</button></div>}{draft&&data&&<>{data.role!=='owner'&&<div className="policy-readonly"><LockKeyhole size={15}/><p>You have {data.role} access. Only the project owner can change these controls.</p></div>}
 {tab==='visibility'&&<><label className="policy-control"><span><strong>Project API usage</strong><small>Who can view this project’s API read count. Personal AI usage and private conversations are never included.</small></span><select value={draft.usageVisibility} disabled={!editable} onChange={e=>change('usageVisibility',e.target.value as Policy['usageVisibility'])}><option value="owner">Owner only</option><option value="members">All project members</option></select></label><div className="policy-metric">{data.usage?<><strong>{data.usage.reads}</strong><span>Project API reads · {data.usage.day} (UTC)</span></>:<span>Project API usage is restricted to the owner.</span>}</div><label className="policy-control"><span><strong>Logs & activity visibility</strong><small>Who can read project activity and policy/API metadata records. Hidden suppresses these views for everyone, including the owner.</small></span><select value={draft.logsVisibility} disabled={!editable} onChange={e=>change('logsVisibility',e.target.value as Policy['logsVisibility'])}><option value="hidden">Hidden</option><option value="owner">Owner only</option><option value="members">All project members</option></select></label></>}
 {tab==='tools'&&<>{toggle('aiEnabled','Project AI','Allow AI requests using this project’s context. Personal AI chats are separate.')}{toggle('importsEnabled','GitHub README imports','Allow public repository README imports. Manual document editing and file imports remain available.')}{toggle('fileSearchEnabled','Document search','Allow keyword searches across shared project document titles and text.')}{toggle('apiEnabled','Project read API','Allow valid project API keys to read shared project data. Disabling pauses access; it does not revoke existing keys.')}<div className="policy-search-box"><h4>Search project documents</h4><p>Keyword search across saved shared documents. Up to 20 matches.</p><form onSubmit={e=>{e.preventDefault();void search()}}><input aria-label="Document keywords" maxLength={120} placeholder="Search a title or phrase" value={query} disabled={!data.policy.fileSearchEnabled||searching} onChange={e=>setQuery(e.target.value)}/><button className="admin-button" disabled={!query.trim()||searching||!data.policy.fileSearchEnabled}><Search size={14}/>{searching?'Searching…':'Search'}</button></form>{!data.policy.fileSearchEnabled&&<p>Document search is disabled for this project.</p>}{searchError&&<p className="policy-error" role="alert">{searchError}</p>}{results&&<div className="policy-results" role="status">{results.length?results.map(v=><article key={v.id}><strong>{v.title}</strong><p>{v.excerpt}</p></article>):<p>No matching documents found.</p>}</div>}</div><h4 className="policy-subtitle">Additional hosted tools</h4>{[['MCP servers','No MCP gateway or server authorization system is configured.'],['Web browsing','No hosted web-search or browsing tool is configured.'],['Image generation','No image-generation provider is configured for project tools.'],['Code interpreter','No hosted code-execution sandbox is configured.']].map(([name,description])=><label className="policy-control policy-disabled" key={name}><span><strong>{name}</strong><small>{description}</small></span><select disabled aria-label={`${name} availability`} value="unavailable"><option value="unavailable">Not available</option></select></label>)}</>}
 {tab==='sharing'&&<><p className="policy-copy">These options concern sending project data to AI providers for additional purposes. Recoord does not offer provider training or evaluation consent controls.</p><Unavailable name="Share model feedback">Provider feedback submission is not integrated. No feedback-sharing program can be enabled here.</Unavailable><Unavailable name="Share evaluation & fine-tuning data">Evaluation datasets, fine-tuning jobs, and associated data-sharing programs are not implemented.</Unavailable><Unavailable name="Share inputs & outputs for training">Recoord has no provider training opt-in setting. Normal AI requests still send messages and context to the configured provider when used; its own terms and settings govern processing.</Unavailable><p className="policy-copy">These controls do not provide free credits or change the provider’s account-level policies.</p></>}
 {tab==='retention'&&<>{toggle('auditEnabled','Policy audit records','Record future project policy changes. This is a limited event trail, not a full compliance audit log.')}<label className="policy-control"><span><strong>API call logging</strong><small>Record metadata for project read API calls. Prompt text, document content, message bodies, keys, and AI outputs are excluded.</small></span><select value={draft.apiLogMode} disabled={!editable} onChange={e=>change('apiLogMode',e.target.value as Policy['apiLogMode'])}><option value="disabled">Disabled</option><option value="per_call">Enabled per call</option><option value="all">All project API reads</option></select></label><p className="policy-copy">Per-call logging requires the request header <code>X-Recoord-Log: 1</code>. API-read logging is independent of policy audit records. These options affect future events only; disabling them does not delete existing records.</p><div className="policy-history"><h4>Policy & API metadata</h4><p>Latest 100 records permitted by the saved log visibility policy.</p>{data.events.length?<ol>{data.events.map(event=><li key={event.id}><div><strong>{event.action.replace(/[._]/g,' ')}</strong><time>{date(event.created)}</time></div><p>{event.details.changedFields?.length?`Changed: ${event.details.changedFields.join(', ')}`:event.details.status?`API response status: ${event.details.status}`:'Project metadata event'}</p><small>By {event.actorName}</small></li>)}</ol>:<div className="policy-empty">{data.policy.logsVisibility==='hidden'?'Records are hidden by this project’s policy.':data.policy.logsVisibility==='owner'&&data.role!=='owner'?'Only the owner can view these records.':'No visible metadata records yet.'}</div>}</div><Unavailable name="Scheduled data retention">Automatic deletion schedules and configurable retention periods are not available. Existing export and deletion controls are listed below.</Unavailable></>}
 {tab==='security'&&<><div className="policy-security-tabs" role="tablist" aria-label="Project security">{[['workload','Workload identity'],['ip','IP allowlist'],['tls','Mutual TLS'],['domains','Domain allowlist']].map(([id,name])=><button key={id} role="tab" aria-selected={security===id} onClick={()=>setSecurity(id)}>{name}</button>)}</div><div role="tabpanel" aria-label={security==='domains'?'Domain allowlist':security}>{security==='domains'?<><h4 className="policy-subtitle">Invitation email domains</h4><p className="policy-copy">Restrict new project invitations and invitation acceptance to exact email domains. Existing members keep their access. An empty list allows any domain.</p><label className="policy-domain-label">Allowed domains<textarea disabled={!editable} rows={4} maxLength={6400} value={domains} onChange={e=>{setDomains(e.target.value);setMessage('')}} placeholder={'example.com\npartner.org'}/></label><p className="policy-copy">One domain per line, up to 25. Do not include URLs, @ signs, or wildcards. Subdomains must be listed separately. This does not verify domain ownership or configure organization SSO.</p><Unavailable name="Embedded chat domain allowlist">Public browser keys and embedded chat widgets are not configured. Invitation email domains do not authorize embedding or restrict browser origins. An embed service must validate allowed website origins before public widget keys can be issued.</Unavailable></>:security==='workload'?<Unavailable name="Workload identity">Federated workload identity requires a trusted issuer and token exchange service. This project has no configured identity federation. Use scoped API keys for supported project reads.</Unavailable>:security==='ip'?<Unavailable name="IP allowlisting">IP restrictions require a trusted gateway and verified client IP handling. Recoord does not currently enforce an IP allowlist for project requests.</Unavailable>:<Unavailable name="Mutual TLS">Client certificate verification requires a configured TLS gateway and certificate lifecycle service. Mutual TLS is not available for this project.</Unavailable>}</div></>}
 {data.role==='owner'&&(tab!=='sharing')&&<div className="policy-save"><span role="status">{message?<><Check size={14}/>{message}</>:dirty?'You have unsaved changes.':draft.updated?`Saved ${date(draft.updated)}`:'Using default project controls.'}</span><button className="admin-button admin-primary" disabled={!dirty||saving||loading} onClick={()=>void save()}>{saving?'Saving…':'Save project controls'}</button></div>}
 </>}</>}</section>
}
