'use client';
import {useEffect,useState} from 'react';
type Person={id:string;name:string;email:string;role:string};
type Task={id:string;title:string;assignee:string|null;due:string|null;status:string;version:number};
type Note={id:string;content:string;authorName?:string;actorName?:string;created:number;mentions?:string;document?:string|null};
type Invite={id:string;email:string;role:string;created:number;project:string;title?:string};
type Board={role:string;members:Person[];tasks:Task[];comments:Note[];decisions:Note[];activities:Note[];documents:{id:string;title:string}[];invitations:Invite[]};
async function call<T>(url:string,data?:unknown):Promise<T>{const r=await fetch(url,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json() as T&{error?:string};if(!r.ok)throw new Error(v.error||'Request failed.');return v}
export function Invitations({joined}:{joined:(p:string)=>void}){const [items,setItems]=useState<Invite[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function load(){try{setItems((await call<{invitations:Invite[]}>('/api/team')).invitations)}catch(e){setError((e as Error).message)}}useEffect(()=>{void load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);return <div className="invite-inbox">{error&&<p role="alert">{error}</p>}{items.map(i=><div key={i.id}><strong>Invitation: {i.title}</strong><p>{i.role} access</p><button disabled={busy} onClick={async()=>{setBusy(true);try{await call('/api/team',{action:'accept',id:i.id});await load();joined(i.project)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Join project</button><button disabled={busy} onClick={async()=>{setBusy(true);try{await call('/api/team',{action:'decline',id:i.id});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Decline</button></div>)}</div>}
export default function Team({project,user,initialDocument}:{project:string;user:string;initialDocument?:string}){
 const [board,setBoard]=useState<Board|null>(null),[section,setSection]=useState(initialDocument?'Discussion':'Tasks'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('editor'),[task,setTask]=useState<Partial<Task>>({title:'',status:'todo',assignee:'',due:''}),[comment,setComment]=useState(''),[document,setDocument]=useState(initialDocument||''),[mentions,setMentions]=useState<string[]>([]),[decision,setDecision]=useState(''),[update,setUpdate]=useState(''),[summary,setSummary]=useState<{summary:string;suggestions:string[]}|null>(null);
 async function load(){setBoard(await call<Board>('/api/team?project='+encodeURIComponent(project)))}
 useEffect(()=>{let active=true;async function refresh(){try{const b=await call<Board>('/api/team?project='+encodeURIComponent(project));if(active)setBoard(b)}catch(e){if(active){setBoard(null);setError((e as Error).message)}}}void refresh();const timer=setInterval(refresh,20000);return()=>{active=false;clearInterval(timer)}},[project]);
 async function act(data:object){setBusy(true);setError('');try{const v=await call<{id?:string}>('/api/team',{...data,project});await load();return v}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 if(!board)return <div className="team-board"><p role="status">{error||'Loading project board…'}</p></div>;
 const edit=board.role!=='viewer',owner=board.role==='owner',name=(id:string|null)=>board.members.find(m=>m.id===id)?.name||'Unassigned',date=(n:number)=>new Date(n).toLocaleString();
 const tagged=board.comments.filter(c=>{try{return JSON.parse(c.mentions||'[]').includes(user)}catch{return false}}).length;
 return <div className="team-board"><div className="team-heading"><div><h2>Coordinate together</h2><p>Your role: <strong>{board.role}</strong> · Shared work refreshes every 20 seconds.</p></div><button className="small-button" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></div><nav className="team-tabs" aria-label="Project board">{['Tasks','Discussion','Decisions','Updates','People'].map(s=><button key={s} className={section===s?'active':''} onClick={()=>setSection(s)}>{s}{s==='Discussion'&&tagged>0?' · '+tagged+' mentions':''}</button>)}</nav>{error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p className="notice-banner" role="status">{notice}</p>}
 {section==='Tasks'&&<><div className="task-columns">{['todo','doing','done'].map(status=><section key={status}><h3>{status==='todo'?'To do':status==='doing'?'In progress':'Done'} <small>{board.tasks.filter(t=>t.status===status).length}</small></h3>{board.tasks.filter(t=>t.status===status).map(t=><article className="team-card" key={t.id}><h4>{t.title}</h4><p>{name(t.assignee)}</p><p className={t.due&&t.due<new Date().toLocaleDateString('en-CA')&&t.status!=='done'?'overdue':''}>{t.due?'Due '+t.due:'No deadline'}</p>{edit&&<button className="small-button" onClick={()=>setTask(t)}>Edit task</button>}</article>)}</section>)}</div>{edit&&<form className="team-form" onSubmit={async e=>{e.preventDefault();const due=new FormData(e.currentTarget).get('due');if(await act({action:'task',...task,due}))setTask({title:'',status:'todo',assignee:'',due:''})}}><h3>{task.id?'Edit task':'Add a task'}</h3><label>Task title<input required maxLength={200} value={task.title||''} onChange={e=>setTask({...task,title:e.target.value})}/></label><div className="form-row"><label>Assigned to<select value={task.assignee||''} onChange={e=>setTask({...task,assignee:e.target.value})}><option value="">Unassigned</option>{board.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Due date<input name="due" type="date" onInput={e=>setTask({...task,due:e.currentTarget.value})} value={task.due||''} onChange={e=>setTask({...task,due:e.target.value})}/></label><label>Status<select value={task.status||'todo'} onChange={e=>setTask({...task,status:e.target.value})}><option value="todo">To do</option><option value="doing">In progress</option><option value="done">Done</option></select></label></div><button className="primary" disabled={busy}>Save task</button>{task.id&&<><button type="button" className="small-button" onClick={()=>setTask({title:'',status:'todo'})}>Cancel edit</button><button type="button" className="danger" disabled={busy} onClick={async()=>{if(confirm('Delete this task permanently?')&&await act({action:'deleteTask',id:task.id}))setTask({title:'',status:'todo'})}}>Delete task</button></>}</form>}</>}
 {section==='Discussion'&&<><label className="team-filter">Discussion for<select value={document} onChange={e=>setDocument(e.target.value)}><option value="">Project</option>{board.documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>{edit&&<form className="team-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'comment',content:comment,document,mentions})){setComment('');setMentions([])}}}><label>Comment<textarea required maxLength={5000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Ask a question or share feedback…"/></label><fieldset><legend>Mention teammates (visible in their project discussion)</legend><div className="mention-options">{board.members.filter(m=>m.id!==user).map(m=><label key={m.id}><input type="checkbox" checked={mentions.includes(m.id)} onChange={e=>setMentions(e.target.checked?[...mentions,m.id]:mentions.filter(x=>x!==m.id))}/>@{m.name}</label>)}</div></fieldset><button className="primary" disabled={busy}>Post comment</button></form>}{board.comments.filter(c=>(c.document||'')===document).map(c=><article className="team-card" key={c.id}><small>{c.authorName||'Former member'} · {date(c.created)}</small><p className="note-content">{c.content}</p><div className="mention-labels">{(JSON.parse(c.mentions||'[]') as string[]).map(id=><span key={id}>@{name(id)}{id===user?' (you)':''}</span>)}</div></article>)}</>}
 {section==='Decisions'&&<>{edit&&<form className="team-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'decision',content:decision}))setDecision('')}}><h3>Record what was agreed</h3><label>Decision and reason<textarea required maxLength={10000} value={decision} onChange={e=>setDecision(e.target.value)} placeholder="What did the team decide, and why?"/></label><button className="primary" disabled={busy}>Record decision</button></form>}{board.decisions.map(d=><article className="team-card" key={d.id}><small>{d.authorName||'Former member'} · {date(d.created)}</small><p className="note-content">{d.content}</p></article>)}</>}
 {section==='Updates'&&<>{edit&&<section className="team-form"><h3>AI progress summary</h3><p>Uses the project goal, context, shared documents, tasks, decisions, and comments. Personal chats stay private. Suggestions need your approval.</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setSummary(await call('/api/summary',{project}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Working…':'Generate summary'}</button>{summary&&<div className="summary-draft"><label>Review summary<textarea value={summary.summary} maxLength={10000} onChange={e=>setSummary({...summary,summary:e.target.value})}/></label><button className="small-button" disabled={busy||!summary.summary.trim()} onClick={async()=>{if(await act({action:'update',content:'AI-assisted update (reviewed): '+summary.summary})){setNotice('Summary shared in updates.');setSummary({...summary,summary:''})}}}>Approve & share update</button>{summary.suggestions.map((s,i)=><div className="suggested-task" key={i}><span>{s}</span><button disabled={busy} onClick={async()=>{if(await act({action:'task',title:s,status:'todo'}))setSummary({...summary,suggestions:summary.suggestions.filter((_,j)=>j!==i)})}}>Approve as task</button></div>)}</div>}</section>}{edit&&<form className="team-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'update',content:update}))setUpdate('')}}><label>Post a team update<textarea required maxLength={10000} value={update} onChange={e=>setUpdate(e.target.value)}/></label><button className="primary" disabled={busy}>Share update</button></form>}<h3>What changed</h3>{board.activities.map(a=><article className="team-card" key={a.id}><small>{a.actorName||'Former member'} · {date(a.created)}</small><p className="note-content">{a.content}</p></article>)}</>}
 {section==='People'&&<><p>Owners manage access and deletion. Editors manage shared work. Viewers can read and export. Project documents and discussions are shared; AI conversations are private.</p>{board.members.map(m=><article className="team-card member-row" key={m.id}><div><strong>{m.name}</strong><p>{m.email}</p></div>{owner&&m.role!=='owner'?<><select aria-label={'Role for '+m.name} value={m.role} disabled={busy} onChange={e=>void act({action:'role',user:m.id,role:e.target.value})}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="danger" disabled={busy} onClick={()=>{if(confirm('Remove '+m.name+' from this project?'))void act({action:'remove',user:m.id})}}>Remove</button></>:<span className="badge">{m.role}</span>}</article>)}{owner&&<><form className="team-form" onSubmit={async e=>{e.preventDefault();const r=await act({action:'invite',email,role});if(r){setEmail('');setNotice('Invitation ready. They must sign in with the invited email. Copy the link below to share it.')}}}><h3>Invite a teammate</h3><label>Email<input type="email" required value={email} maxLength={254} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="editor">Editor</option><option value="viewer">Viewer</option></select></label><p>Invitations expire after 7 days. No email is sent automatically.</p><button className="primary" disabled={busy}>Create invitation</button></form>{board.invitations.map(i=><article className="team-card" key={i.id}><strong>{i.email}</strong><p>{i.role} · {Date.now()-i.created>7*86400000?'Expired':'Pending'}</p><button className="small-button" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin+'/?invite='+i.id);setNotice('Invitation link copied.')}catch{setNotice('Share this link: '+window.location.origin+'/?invite='+i.id)}}}>Copy invitation link</button><button className="danger" disabled={busy} onClick={()=>void act({action:'revoke',id:i.id})}>Revoke</button></article>)}</>}</>}
 </div>
}
