'use client';
import {useEffect,useRef,useState} from 'react';
import './admin-tools.css';
type Usage={monthlyLimit:number;alertAt:number;alertsEnabled:boolean;month:string;requests:number;remaining:number;resetsAt:string};
async function api(init?:RequestInit):Promise<Usage>{const res=await fetch('/api/usage-preferences',{...init,headers:{'Content-Type':'application/json',...init?.headers}});const value=await res.json() as Usage&{error?:string};if(!res.ok)throw new Error(value.error||'Could not load your monthly limit.');return value}
export default function UsageControls(){const [data,setData]=useState<Usage|null>(null),[limit,setLimit]=useState(''),[threshold,setThreshold]=useState(''),[alerts,setAlerts]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);const lock=useRef(false);
 useEffect(()=>{const c=new AbortController();setError('');api({signal:c.signal}).then(v=>{setData(v);setLimit(String(v.monthlyLimit));setThreshold(String(v.alertAt));setAlerts(v.alertsEnabled)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[refresh]);
 const dirty=!!data&&(Number(limit)!==data.monthlyLimit||Number(threshold)!==data.alertAt||alerts!==data.alertsEnabled);const valid=Number.isInteger(Number(limit))&&Number(limit)>=1&&Number(limit)<=1000000&&Number.isInteger(Number(threshold))&&Number(threshold)>=1&&Number(threshold)<=100;
 async function save(){if(lock.current||!valid)return;lock.current=true;setBusy(true);setError('');setStatus('');try{const v=await api({method:'PATCH',body:JSON.stringify({monthlyLimit:Number(limit),alertAt:Number(threshold),alertsEnabled:alerts})});setData(v);setLimit(String(v.monthlyLimit));setThreshold(String(v.alertAt));setAlerts(v.alertsEnabled);setStatus('Monthly request limit saved.')}catch(e){setError(e instanceof Error?e.message:'Could not save limit.')}finally{lock.current=false;setBusy(false)}}
 return <section className="usage-controls"><h3>Monthly AI request attempt limit</h3><p className="admin-muted">Set a personal cap on reserved AI request attempts across your account. This is a request allowance, not a currency budget.</p>{error&&<div className="admin-error" role="alert">{error}<button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>}{!data&&!error&&<p role="status" className="admin-muted">Loading your monthly allowance…</p>}{data&&<><div className="usage-month"><div><strong>{data.requests}</strong><span> / {data.monthlyLimit.toLocaleString()} request attempts this month</span></div><progress value={Math.min(data.requests,data.monthlyLimit)} max={data.monthlyLimit} aria-label="Monthly AI request allowance"/><p>{data.remaining.toLocaleString()} remaining · Resets {new Date(data.resetsAt).toLocaleString()}</p></div>{data.alertsEnabled&&data.requests/data.monthlyLimit*100>=data.alertAt&&<div className="usage-alert" role="status">You have used {Math.min(100,Math.round(data.requests/data.monthlyLimit*100))}% of your monthly AI request allowance.</div>}<form className="usage-form" onSubmit={e=>{e.preventDefault();void save()}}><label>Monthly request attempt cap<input type="number" min={1} max={1000000} step={1} required disabled={busy} value={limit} onChange={e=>{setLimit(e.target.value);setStatus('')}}/></label><label className="usage-alert-toggle"><input type="checkbox" checked={alerts} disabled={busy} onChange={e=>{setAlerts(e.target.checked);setStatus('')}}/><span>Show an in-app usage alert</span></label><label>Alert at (% of allowance)<input type="number" min={1} max={100} step={1} required value={threshold} disabled={busy} onChange={e=>{setThreshold(e.target.value);setStatus('')}}/></label><p className="admin-muted">Counts begin when monthly controls are introduced and reset each UTC calendar month. Failed provider calls and daily-limit-blocked attempts can count. Alerts appear in Recoord; no email or external notification is sent. Lowering your cap below current usage pauses new AI requests until the next UTC month or until you raise the cap.</p><div className="people-form-actions"><button className="admin-button admin-primary" disabled={!dirty||!valid||busy}>{busy?'Saving…':'Save monthly limit'}</button><span className="admin-success" role="status">{status}</span></div></form></>}<div className="usage-provider-note"><strong>Provider limits & billing</strong><p>Provider tokens per minute, requests per minute, batch capacity, dollar budgets, billing tiers, and automatic credit reload are not configurable here. Provider and shared-site limits may still restrict requests below your personal cap.</p></div></section>
}
