'use client';
import {defaults,type Preferences} from './preferences';
import {useState} from 'react';
import {UserRound,Sparkles,Database,Info,LogOut,Download,ArrowUpRight,Code2,ShieldCheck,ChevronRight,SlidersHorizontal,Blocks,Keyboard,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type SettingsSection='account'|'appearance'|'behavior'|'integrations'|'shortcuts'|'ai'|'data'|'about';
type Props={preferences:Preferences;onPreferences:(p:Preferences)=>void;preferenceStatus:string;onIntegrations:()=>void;open:boolean;onOpenChange:(open:boolean)=>void;section:SettingsSection;onSectionChange:(section:SettingsSection)=>void;user:{name:string;email:string}|null;preview:boolean;ready:boolean;provider:string;model:string;onSignOut:()=>Promise<void>;onSignIn:()=>void;onExport:()=>Promise<void>;onDelete:()=>Promise<void>;deleteText:string;onDeleteTextChange:(value:string)=>void;error:string;onMobileClose:()=>void};
export default function WorkspaceSettings(p:Props){
 const [query,setQuery]=useState('');
 const [confirmDelete,setConfirmDelete]=useState(false),[working,setWorking]=useState('');
 async function run(action:string,work:()=>Promise<void>){setWorking(action);try{await work()}finally{setWorking('')}}
 const tabs=[{id:'account',label:'Profile & access',icon:UserRound,keywords:'name email sign in session'},{id:'appearance',label:'Appearance',icon:SlidersHorizontal,keywords:'density compact text size motion accessibility'},{id:'behavior',label:'Chat & projects',icon:Sparkles,keywords:'enter send keyboard grid list layout'},{id:'ai',label:'AI & privacy',icon:ShieldCheck,keywords:'provider model context'},{id:'integrations',label:'Integrations',icon:Blocks,keywords:'github calendar import export'},{id:'data',label:'Your data',icon:Database,keywords:'export delete download'},{id:'shortcuts',label:'Keyboard shortcuts',icon:Keyboard,keywords:'search navigate send'},{id:'about',label:'About Recoord',icon:Info,keywords:'source license github help'}] as const;
 const visible=tabs.filter(t=>(t.label+' '+t.keywords).toLowerCase().includes(query.trim().toLowerCase()));
 function preference<K extends keyof Preferences>(key:K,value:Preferences[K]){p.onPreferences({...p.preferences,[key]:value})}

 function close(open:boolean){if(working)return;p.onOpenChange(open);if(!open){setConfirmDelete(false);p.onDeleteTextChange('')}}
 return <Dialog open={p.open} onOpenChange={close}><DialogContent className="recoord-dialog workspace-settings" onCloseAutoFocus={e=>{if(window.matchMedia('(max-width:850px)').matches){e.preventDefault();p.onMobileClose()}}}><header className="settings-header"><DialogTitle>Settings</DialogTitle><DialogDescription>Make Recoord work your way.</DialogDescription></header><div className="settings-shell"><aside className="settings-sidebar"><label className="settings-search"><Search size={15}/><input aria-label="Search settings" placeholder="Find a setting…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="settings-group-label">Personal settings</span>
 <nav className="settings-navigation" aria-label="Settings sections">{visible.map(t=><button key={t.id} aria-current={p.section===t.id?'page':undefined} onClick={()=>p.onSectionChange(t.id)}><t.icon size={16}/>{t.label}</button>)}</nav>{!visible.length&&<p className="settings-copy" role="status">No settings found.</p>}<span className="settings-device">Preferences apply to this browser.</span></aside>
 <section className="settings-content" aria-label={tabs.find(t=>t.id===p.section)?.label}><h2>{tabs.find(t=>t.id===p.section)?.label}</h2>
 {p.section==='appearance'&&<><p className="settings-copy">A quieter workspace, tuned to you.</p><label className="settings-row"><span><strong>Interface density</strong><p>Adjust navigation and project spacing.</p></span><select value={p.preferences.density} onChange={e=>preference('density',e.target.value as Preferences['density'])}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label className="settings-row"><span><strong>Reading size</strong><p>Text in conversations and documents.</p></span><select value={p.preferences.text} onChange={e=>preference('text',e.target.value as Preferences['text'])}><option value="standard">Standard</option><option value="large">Large</option></select></label><label className="settings-row"><span><strong>Motion</strong><p>Reduce animation and transitions.</p></span><select value={p.preferences.motion} onChange={e=>preference('motion',e.target.value as Preferences['motion'])}><option value="system">Follow device</option><option value="reduced">Reduce motion</option></select></label></>}
 {p.section==='behavior'&&<><label className="settings-row"><span><strong>Send a message</strong><p>Shift + Enter always adds a new line.</p></span><select value={p.preferences.send} onChange={e=>preference('send',e.target.value as Preferences['send'])}><option value="enter">Enter</option><option value="modifier">⌘ / Ctrl + Enter</option></select></label><label className="settings-row"><span><strong>Project layout</strong><p>Remember your preferred view on Home.</p></span><select value={p.preferences.layout} onChange={e=>preference('layout',e.target.value as Preferences['layout'])}><option value="grid">Grid</option><option value="list">List</option></select></label></>}
 {p.section==='integrations'&&<><p className="settings-copy">Bring context in. Take your next steps with you.</p><div className="settings-row"><div><strong>GitHub README import</strong><p>Save a public repository’s README as a shared project document. Each import is a one-time copy.</p></div></div><div className="settings-row"><div><strong>Calendar export</strong><p>Download open task deadlines for Apple Calendar, Google Calendar, or Outlook. Changes do not sync automatically.</p></div></div><button className="small-button" onClick={p.onIntegrations}>Open integration tools <ArrowUpRight size={15}/></button></>}
 {p.section==='shortcuts'&&<><dl className="settings-details"><div><dt>Search workspace</dt><dd><kbd>⌘ / Ctrl K</kbd></dd></div><div><dt>Close a dialog</dt><dd><kbd>Esc</kbd></dd></div><div><dt>Move between controls</dt><dd><kbd>Tab / Shift Tab</kbd></dd></div><div><dt>Send message</dt><dd><kbd>{p.preferences.send==='enter'?'Enter':'⌘ / Ctrl Enter'}</kbd></dd></div><div><dt>New line</dt><dd><kbd>Shift Enter</kbd></dd></div></dl></>}
 {p.section==='account'&&<><div className="settings-profile"><span className="settings-avatar">{p.preview?'P':(p.user?.name.trim()[0]||'R').toUpperCase()}</span><div><h3>{p.preview?'Preview account':p.user?.name||'Welcome to Recoord'}</h3><p>{p.preview?'Local testing only':p.user?.email||'Sign in to save your projects and conversations.'}</p></div></div>{p.preview?<div className="settings-callout"><Info size={18}/><p>This is a local test account, separate from your live Recoord account. Preview projects are not your live projects.</p></div>:p.user?<div className="settings-callout"><ShieldCheck size={18}/><p>You’re signed in with ChatGPT. Your name and email come from that account.</p></div>:null}<div className="settings-row"><div><strong>{p.user?'Session':'Get started'}</strong><p>{p.user?'Sign out on this browser. Your saved work stays in Recoord.':'Your AI chats are private. Project documents are shared with project members.'}</p></div>{p.user?<button className="small-button" disabled={!!working} onClick={()=>void run('signout',p.onSignOut)}><LogOut size={15}/>{working==='signout'?'Signing out…':'Sign out'}</button>:<button className="primary" onClick={p.onSignIn}>Sign in</button>}</div></>}
 {p.section==='ai'&&<><div className="settings-status"><span className={'connection-dot '+(p.ready?'is-ready':'')}/><strong>{p.ready?'AI is ready':'AI is not connected'}</strong></div><dl className="settings-details"><div><dt>Provider</dt><dd>{p.ready?p.provider:'Not configured'}</dd></div><div><dt>Model</dt><dd>{p.ready?p.model:'Not configured'}</dd></div></dl><p className="settings-copy">{p.ready?'When you ask AI for a reply, your message, recent conversation, and project context are sent to this provider.':'The site owner configures the AI provider. Projects and documents work even when AI is unavailable.'}</p><div className="settings-callout"><ShieldCheck size={18}/><p>Your personal AI conversations stay private. Saving a reply as a project document shares that document with the project.</p></div></>}
 {p.section==='data'&&<><div className="settings-row"><div><strong>Export your workspace</strong><p>Download a JSON copy of accessible project work and your private conversations.</p></div><button className="small-button" disabled={!p.user||!!working} onClick={()=>void run('export',p.onExport)}><Download size={15}/>{working==='export'?'Exporting…':'Export data'}</button></div><p className="settings-copy">Saved content is stored on Recoord’s hosting service. Open-source code does not mean messages stay on your device.</p><div className="settings-danger"><button className="danger-disclosure" aria-expanded={confirmDelete} onClick={()=>{setConfirmDelete(!confirmDelete);p.onDeleteTextChange('')}}><span>Delete saved content</span><ChevronRight size={15} className={confirmDelete?'expanded':''}/></button>{confirmDelete&&<div><p>This permanently deletes projects you own for everyone, your private chats, and your project memberships. Contributions to other people’s projects remain under “Former member.” Your ChatGPT account is unchanged, and daily usage counters remain.</p><label>Type DELETE MY DATA to confirm<input value={p.deleteText} onChange={e=>p.onDeleteTextChange(e.target.value)} placeholder="DELETE MY DATA" autoComplete="off"/></label><button className="danger-action" disabled={!p.user||p.deleteText!=='DELETE MY DATA'||!!working} onClick={()=>void run('delete',p.onDelete)}>{working==='delete'?'Deleting…':'Permanently delete saved content'}</button></div>}</div></>}
 {p.section==='about'&&<><div className="settings-about"><img src="/recoord-mark.svg" alt="" width={44} height={44}/><div><h3>Recoord</h3><p>A shared space for projects. A private space to think.</p></div></div><a className="settings-link" href="https://github.com/alhajahmad/Recoord" target="_blank" rel="noreferrer"><Code2 size={19}/><span><strong>View on GitHub</strong><small>Explore the code, report an issue, or contribute.</small></span><ArrowUpRight size={17}/></a><a className="settings-link" href="/recoord-source.zip" download><Download size={19}/><span><strong>Download source</strong><small>Includes the self-hosting guide.</small></span><ArrowUpRight size={17}/></a><p className="settings-copy">MIT-licensed application. Model licenses and provider charges are separate.</p></>}
 {(p.section==='appearance'||p.section==='behavior')&&<div className="settings-save-status"><span role="status">{p.preferenceStatus}</span><button onClick={()=>p.onPreferences({...defaults})}>Reset preferences</button></div>}</section></div>{p.error&&<p className="form-error" role="alert">{p.error}</p>}</DialogContent></Dialog>
}
