import { sqliteTable,text,integer,index } from "drizzle-orm/sqlite-core";
export const conversations=sqliteTable("conversations",{id:text("id").primaryKey(),owner:text("owner").notNull(),project:text("project"),title:text("title").notNull(),updated:integer("updated").notNull()},t=>[index("idx_conversations_owner_updated").on(t.owner,t.updated)]);
export const messages=sqliteTable("messages",{id:text("id").primaryKey(),conversation:text("conversation").notNull().references(()=>conversations.id,{onDelete:"cascade"}),role:text("role").notNull(),content:text("content").notNull(),created:integer("created").notNull()},t=>[index("idx_messages_conversation_created").on(t.conversation,t.created)]);
export const quotas=sqliteTable("quotas",{key:text("key").primaryKey(),count:integer("count").notNull()});

export const projects=sqliteTable("projects",{id:text("id").primaryKey(),owner:text("owner").notNull(),title:text("title").notNull(),goal:text("goal").notNull().default(""),context:text("context").notNull().default(""),updated:integer("updated").notNull()},t=>[index("idx_projects_owner_updated").on(t.owner,t.updated)]);
export const documents=sqliteTable("documents",{id:text("id").primaryKey(),owner:text("owner").notNull(),project:text("project").notNull().references(()=>projects.id,{onDelete:"cascade"}),title:text("title").notNull(),content:text("content").notNull(),version:integer("version").notNull().default(1),updated:integer("updated").notNull()},t=>[index("idx_documents_owner_project").on(t.owner,t.project)]);
export const drafts=sqliteTable("drafts",{id:text("id").primaryKey(),owner:text("owner").notNull(),project:text("project"),content:text("content").notNull(),updated:integer("updated").notNull()},t=>[index("idx_drafts_owner_project").on(t.owner,t.project)]);

export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull()});
export const members=sqliteTable('members',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),user:text('user').notNull(),role:text('role').notNull()});
export const invitations=sqliteTable('invitations',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),email:text('email').notNull(),role:text('role').notNull(),created:integer('created').notNull()});
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),title:text('title').notNull(),assignee:text('assignee'),due:text('due'),status:text('status').notNull().default('todo'),version:integer('version').notNull().default(1),updated:integer('updated').notNull()});
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),document:text('document'),author:text('author').notNull(),content:text('content').notNull(),mentions:text('mentions').notNull().default('[]'),created:integer('created').notNull()});
export const decisions=sqliteTable('decisions',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),author:text('author').notNull(),content:text('content').notNull(),created:integer('created').notNull()});
export const activities=sqliteTable('activities',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),actor:text('actor').notNull(),content:text('content').notNull(),created:integer('created').notNull()});
