import { sqliteTable,text,integer,index,uniqueIndex } from "drizzle-orm/sqlite-core";
export const conversations=sqliteTable("conversations",{id:text("id").primaryKey(),owner:text("owner").notNull(),project:text("project"),title:text("title").notNull(),updated:integer("updated").notNull()},t=>[index("idx_conversations_owner_updated").on(t.owner,t.updated)]);
export const messages=sqliteTable("messages",{id:text("id").primaryKey(),conversation:text("conversation").notNull().references(()=>conversations.id,{onDelete:"cascade"}),role:text("role").notNull(),content:text("content").notNull(),created:integer("created").notNull()},t=>[index("idx_messages_conversation_created").on(t.conversation,t.created)]);
export const quotas=sqliteTable("quotas",{key:text("key").primaryKey(),count:integer("count").notNull()});

export const projects=sqliteTable("projects",{id:text("id").primaryKey(),owner:text("owner").notNull(),title:text("title").notNull(),goal:text("goal").notNull().default(""),context:text("context").notNull().default(""),updated:integer("updated").notNull()},t=>[index("idx_projects_owner_updated").on(t.owner,t.updated)]);
export const documents=sqliteTable("documents",{id:text("id").primaryKey(),owner:text("owner").notNull(),project:text("project").notNull().references(()=>projects.id,{onDelete:"cascade"}),title:text("title").notNull(),content:text("content").notNull(),version:integer("version").notNull().default(1),updated:integer("updated").notNull()},t=>[index("idx_documents_owner_project").on(t.owner,t.project)]);
export const drafts=sqliteTable("drafts",{id:text("id").primaryKey(),owner:text("owner").notNull(),project:text("project"),content:text("content").notNull(),updated:integer("updated").notNull()},t=>[index("idx_drafts_owner_project").on(t.owner,t.project)]);

export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull()});
export const members=sqliteTable('members',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),user:text('user').notNull(),role:text('role').notNull()});
export const invitations=sqliteTable('invitations',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),email:text('email').notNull(),role:text('role').notNull(),created:integer('created').notNull()});
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),title:text('title').notNull(),assignee:text('assignee'),due:text('due'),status:text('status').notNull().default('todo'),version:integer('version').notNull().default(1),updated:integer('updated').notNull()});
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),document:text('document'),author:text('author').notNull(),content:text('content').notNull(),mentions:text('mentions').notNull().default('[]'),created:integer('created').notNull()});
export const decisions=sqliteTable('decisions',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),author:text('author').notNull(),content:text('content').notNull(),created:integer('created').notNull()});
export const activities=sqliteTable('activities',{id:text('id').primaryKey(),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),actor:text('actor').notNull(),content:text('content').notNull(),created:integer('created').notNull()});
export const profileDetails=sqliteTable('profile_details',{id:text('id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),bio:text('bio').notNull().default(''),title:text('title').notNull().default(''),company:text('company').notNull().default(''),location:text('location').notNull().default(''),website:text('website').notNull().default(''),photo:text('photo').notNull().default(''),username:text('username'),visibility:text('visibility').notNull().default('private'),skills:text('skills').notNull().default(''),lookingFor:text('looking_for').notNull().default('')},t=>[uniqueIndex('idx_profile_username').on(t.username)]);

export const connections=sqliteTable('connections',{id:text('id').primaryKey(),sender:text('sender').notNull().references(()=>profiles.id,{onDelete:'cascade'}),recipient:text('recipient').notNull().references(()=>profiles.id,{onDelete:'cascade'}),status:text('status').notNull().default('pending'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('idx_connections_sender').on(t.sender),index('idx_connections_recipient').on(t.recipient)]);
export const blocks=sqliteTable('blocks',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>profiles.id,{onDelete:'cascade'}),target:text('target').notNull().references(()=>profiles.id,{onDelete:'cascade'}),created:integer('created').notNull()},t=>[index('idx_blocks_owner').on(t.owner),index('idx_blocks_target').on(t.target)]);
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),author:text('author').notNull().references(()=>profiles.id,{onDelete:'cascade'}),content:text('content').notNull(),image:text('image').notNull().default(''),video:text('video').notNull().default(''),projectTitle:text('project_title').notNull().default(''),workLink:text('work_link').notNull().default(''),audience:text('audience').notNull().default('public'),created:integer('created').notNull()},t=>[index('idx_posts_created').on(t.created),index('idx_posts_author').on(t.author)]);
export const socialComments=sqliteTable('social_comments',{id:text('id').primaryKey(),author:text('author').notNull().references(()=>profiles.id,{onDelete:'cascade'}),targetType:text('target_type').notNull(),target:text('target').notNull(),content:text('content').notNull(),audience:text('audience').notNull().default('public'),created:integer('created').notNull()},t=>[index('idx_social_comments_target').on(t.targetType,t.target,t.created)]);
export const directMessages=sqliteTable('direct_messages',{id:text('id').primaryKey(),sender:text('sender').notNull().references(()=>profiles.id,{onDelete:'cascade'}),recipient:text('recipient').notNull().references(()=>profiles.id,{onDelete:'cascade'}),content:text('content').notNull(),created:integer('created').notNull()},t=>[index('idx_direct_sender').on(t.sender,t.created),index('idx_direct_recipient').on(t.recipient,t.created)]);
export const developerKeys=sqliteTable('developer_keys',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>profiles.id,{onDelete:'cascade'}),project:text('project').notNull().references(()=>projects.id,{onDelete:'cascade'}),label:text('label').notNull(),prefix:text('prefix').notNull(),hash:text('hash').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),lastUsed:integer('last_used'),revoked:integer('revoked'),rateWindow:integer('rate_window').notNull().default(0),readCount:integer('read_count').notNull().default(0)},t=>[uniqueIndex('idx_developer_key_hash').on(t.hash),index('idx_developer_key_owner').on(t.owner)]);
