import {identity,db,failure,body,text,HttpError} from '../shared';
import {socialJson,socialViewer,socialBlocked,visiblePost,sharingQuota,sharingId,requireSharedProfile} from '../posts/route';
async function targetOwner(type:string,target:string,user:string){
 if(type==='post')return String((await visiblePost(target,user)).author);
 if(type!=='profile')throw new HttpError(400,'Choose a post or profile.');
 if(!user)throw new HttpError(401,'Please sign in to view profile comments.');
 const p=await db().prepare('SELECT p.id,d.visibility FROM profiles p LEFT JOIN profile_details d ON p.id=d.id WHERE p.id=?').bind(target).first();
 if(!p||(p.id!==user&&p.visibility!=='members')||await socialBlocked(user,target))throw new HttpError(404,'Profile not available.');return target;
}
async function comments(type:string,target:string,user:string,owner:string){const rows=(await db().prepare("SELECT c.id,c.author,u.name,CASE WHEN d.visibility='members' OR c.author=? THEN d.username ELSE NULL END AS username,CASE WHEN d.visibility='members' OR c.author=? THEN d.photo ELSE '' END AS photo,c.content,c.audience,c.created FROM social_comments c JOIN profiles u ON u.id=c.author LEFT JOIN profile_details d ON d.id=c.author WHERE c.target_type=? AND c.target=? AND (c.audience='public' OR (c.audience='private' AND (c.author=? OR ?=?))) AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.owner=? AND b.target=c.author) OR (b.target=? AND b.owner=c.author)) ORDER BY c.created,c.id LIMIT 200").bind(user,user,type,target,user,user,owner,user,user).all()).results;return rows.map(c=>({...c,canDelete:c.author===user||owner===user}))}
export async function GET(r:Request){try{const u=await socialViewer(),q=new URL(r.url).searchParams,type=text(q.get('targetType'),10,true),target=text(q.get('target'),200,true),owner=await targetOwner(type,target,u);return socialJson({comments:await comments(type,target,u,owner)})}catch(e){return failure(e)}}
export async function POST(r:Request){try{const u=await identity(r),d=await body(r),type=text(d.targetType,10,true),target=text(d.target,200,true),owner=await targetOwner(type,target,u),content=text(d.content,2000,true).trim(),audience=d.audience??'public',id=sharingId(d.id);if(audience!=='public'&&audience!=='private')throw new HttpError(400,'Choose a public or private comment.');if(audience==='public')await requireSharedProfile(u);
 const old=await db().prepare('SELECT * FROM social_comments WHERE id=?').bind(id).first();if(old){if(old.author!==u||old.target_type!==type||old.target!==target||old.content!==content||old.audience!==audience)throw new HttpError(409,'That comment ID has already been used.');return socialJson({comments:await comments(type,target,u,owner)})}
 await sharingQuota(u);await db().prepare('INSERT INTO social_comments (id,author,target_type,target,content,audience,created) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,u,type,target,content,audience,Date.now()).run();const saved=await db().prepare('SELECT * FROM social_comments WHERE id=?').bind(id).first();if(!saved||saved.author!==u||saved.target_type!==type||saved.target!==target||saved.content!==content||saved.audience!==audience)throw new HttpError(409,'That comment ID has already been used.');return socialJson({comments:await comments(type,target,u,owner)});
 }catch(e){return failure(e)}}
export async function DELETE(r:Request){try{const u=await identity(r),d=await body(r),id=text(d.id,100,true),comment=await db().prepare('SELECT * FROM social_comments WHERE id=?').bind(id).first();if(!comment)throw new HttpError(404,'Comment not available.');if(comment.author!==u){const owner=await targetOwner(String(comment.target_type),String(comment.target),u);if(owner!==u)throw new HttpError(403,'Only the author or page owner can remove this comment.');}await db().prepare('DELETE FROM social_comments WHERE id=?').bind(id).run();return socialJson({ok:true})}catch(e){return failure(e)}}
